contrib/fedpeg/withdrawwatch.py

Otherwise you get an error every time you restart withdrawwatch.py

Fix spent_from_log formatting

---

src/pow.cpp

Include missing ENABLE_WALLET guards to avoid building wallet/including bdb if --disable-wallet is specified.

Guard wallet code in pow.cpp with ENABLE_WALLET

---

contrib/sidechain-manipulation.py

Since '%d' was used, refund values are being truncated from display. This fix uses the floating point '%.16g' format flag instead, the same flag used for displaying the value.

Do not truncate refund amount when printing debug data to the user

---

share/genbuild.sh

Backport fix to #31 from bitcoin.

build: if there's no recent git tag, don't spew error messages

---

contrib/sidechain-manipulation.py

- Add support for command line arguments to the sidechain manipulation script. argparse requires Python 2.7 or 3.2+.
- Add support for unlocking mainchain wallet when running send-to-sidechain.
- Add various bits of help text, some of which may not be quite right.

Add CL flag support to sidechain manipulation script

---

src/Makefile.am

Right now, running 'make src/bitcoind' in alpha gives a very misleading error message about include files. What's actually happening is, there's no rule for 'bitcoind' in the Makefile, but because there's a source file named bitcoind.cpp, make is inventing a default rule, which doesn't work.
So let's make an overriding rule that displays a helpful error. (I did this for the three binaries I have run into this building; we can add more if there are more I forgot about.)

Give a nice error for "make bitcoind", instead of a misleading one.

---

src/Makefile.test.include
src/chainparams.cpp
src/chainparams.h
src/chainparamsbase.cpp
src/chainparamsbase.h
src/init.cpp
src/main.cpp
src/main.h
src/test/genesis_tests.cpp

Add commandline flag to set genesis block script destination

---

src/txdb.cpp

We still verify the headers of the last -checkblocks blocks.

Disable proof checking for all blocks on load

---

src/wallet.h

After someone sent a transaction using a wrong scanning key to an alphad wallet, "CWallet::GetCredit() : value out of range" errors were returned on attempts to get balance or create new outgoing transactions. (because at https://github.com/ElementsProject/elements/blob/292f923d0341a7f33a85e8e73cc955697c7aa070/src/wallet.h#L938 the amount returned is -1 if unblinding fails)
This change causes such outputs to be ignored, thus preventing wallet from being locked down this way.

Fixed errors after receiving a tx with wrong scanning key

---

src/coins.cpp
src/main.cpp
src/miner.cpp
src/rpcclient.cpp
src/rpcrawtransaction.cpp

This PR includes my attempts to get alphad to work in regtest mode. What I'm trying to do is generate 100 blocks and then `createrawtransaction` to issue a new asset.
1. I got `CheckTransaction: vTxFees bigger than vout` by just running it without any modifications. This seems due to `>` check being reversed in `CheckTransaction` in `main.cpp`.
2. After the change above alphad still fails with `ConnectBlock: coinbase pays too much` on startup. I relaxed the checks in `CCoinsViewCache::VerifyAmounts` in `coins.cpp` so they now allow coinbase with null asset id. Not sure if it's correct, but at least it makes the server start.
3. However it now SIGSEGVs on `setgenerate true` due to `vout` being too small in `miner.cpp`. Moving the `resize` after the change to `mBlockReward` makes …

Assets: Attempts to fix regtest

---

contrib/fedpeg/constants.py

The instructions for sidechain manipulation from elementsproject.org says
"
**Note:** *If you set a custom RPCUSER and RPCPASS in the earlier step, you’ll need to edit ./contrib/sidechain-manipulation.py now to reflect those values somewhere around lines 9 and 10.*
"
This is both no longer true and rather annoying. This patch changes just the `FedpegConstants`, `sidechain_url` and `bitcoin_url`, to contain optional user and password from the environment. Names were selected based on elementsproject.org documentation wording.
`RPC_USER`
`RPC_PASS`

Allow sidechain-manipulation to use RPC_USER and RPC_PASS from environment

---

qa/rpc-tests/confidential_transactions.py
src/wallet/rpcwallet.cpp

This matches `listreceivedby*` and adds testing conditions as well.

listunspent: don't list outputs with unknown amounts

---

configure.ac

QT does not get the C++11 std flag properly with the 0.13.1 version. This commit by @theuni fixes.
[from https://github.com/bitcoin/bitcoin/pull/9169]
OBJCXX's std flags don't get defined by our cxx macro. Rather than hard-coding
to c++11, just force OBJCXX to be the same as CXX unless the user specified
otherwise.
Github-Pull: #9169
Rebased-From: 70266e98292bf9c8f019ca4b11d681b575f71448

build: fix qt5.7 build under macOS

---

src/bitcoind.cpp

Fixed the error message when trying to use RPC commands with elementsd.

[Trivial] Change 'bitcoin-cli' to 'elements-cli' in error message

---

src/wallet/rpcwallet.cpp

This commit is meant to be squashed into 'Add withdraw-manipulation RPCs' when we rebase on top of 0.14. It saves us 1 line and looks slightly more clear.

Trivial: Move SendMoney wrapper below funcion definition

---

src/wallet/rpcwallet.cpp

Fixes help message for `claimpegin` rpc command. Previously it was giving a hash as an example, when a raw transaction is really required: 
https://github.com/ElementsProject/elementsproject.org/pull/35

Fix claimpegin help msg

---

src/util.cpp

It's meant to be written to disk as a safety measure, so ignore command line arguments that nullify it.

Don't redirect audit.log output with -printtoconsole

---

contrib/elements-devtools/generate_element_blocks.py

Adding script to generate elements blocks in 1 of 1 regtest mode. Usage: 
```
$ python generate_element_blocks.py --num=100 --datadir=$BETADATADIR
```

Adding script to generate element blocks

---

qa/rpc-tests/confidential_transactions.py
src/rpc/misc.cpp

General tool to create blinded addresses given an unblinded address and blinding key pair.
Intended for use with multisig addresses, since the user should not be changing blinding keys of CT addresses it already has created.

new createblindedaddress call to gen CT address

---

qa/rpc-tests/confidential_transactions.py
src/rpc/rawtransaction.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp

There was some leftover static blinding key code that meant blinding a partially-blinded transaction would fail because it would attempt to deblind an output using the deprecated static blinding key.
I fixed this, added a test, and removed the last of the static blinding key code.

Fix transaction re-blinding, remove legacy static key

---

src/wallet/rpcwallet.cpp

These values were returned before they were returned output-by-output in `ListTransactions` which covers both `listtransactions` and `gettransaction` use-cases.

remove extraneous blinder returns for WalletTxToJSON

---

qa/rpc-tests/getchaintips.py
qa/rpc-tests/wallet.py
src/Makefile.test.include
src/blind.cpp
src/blind.h
src/main.cpp
src/miner.cpp
src/test/blind_tests.cpp
src/test/verify_amounts_tests.cpp

Also fixed the coinbase value checking for values out of range.

fixup disallowing 0-value spendable outputs

---

src/qt/paymentrequestplus.cpp
src/wallet/test/crypto_tests.cpp

Without this PR elements doesn't compile on my machine with openssl 1.1.0e. (`wallet/test/crypto_tests.cpp:45:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined`)

[backport] Update for OpenSSL 1.1 API

---

src/rpc/rawtransaction.cpp

1. rawblindrawtransaction
- command line
add inputamount, inputasset, inputassetblinder and ignoreblindfail
change totalblinder to simple value
set totalblinder, ignoreblindfail to optional
- parameter
add optional to ignoreblindfail
2. blindrawtransaction
- command line
move ignoreblindfail to 2nd
change totalblinder to simple value
set totalblinder, array of assetcommitment, ignoreblindfail to optional
- parameter
add optional to ignoreblindfail
fix assetcommitments to assetcommitment

Trivial: Fix help text in rpc/rawtransaction.cpp

---

src/wallet/rpcwallet.cpp

Pegins during IBD will almost deterministically fail, so they should be disabled.

Disable claimpegin during IBD

---

src/main.cpp

Currently a node may try to peg-in bitcoin funds using a lock that is not explicit bitcoin. Simply don't track these.
For a multi-peg/asset pegging scenario we can generalize this via pegging cleanup.

Only track locks with explicit asset types that are bitcoin

---

src/main.cpp
src/primitives/transaction.cpp
src/test/blind_tests.cpp
src/test/verify_amounts_tests.cpp
src/wallet/rpcwallet.cpp

Previous logic, aside from allowing 0-fee outputs, was completely duplicated in other sections of the code.
The value-checking of outputs is already done in `CheckTransaction`, `VerifyAmounts` and `VerifyCoinbaseAmount`, so no need to check again in another context.
I can not recall why we disallowed 0-value fees initially, but the new logic is cleaner since we now always allow 0-value outputs as long as they're `IsUnspendable`, which fees are a smaller subset of.
I have also added more tests.

[HF] Fee output logic cleanup, allow 0-value fees

---

qa/rpc-tests/confidential_transactions.py
src/rpc/misc.cpp

@Christewart we found this to be more useful downstream, so we switched.

have createblindedaddress use blinding pubkey instead

---

qa/rpc-tests/invalidateblock.py
qa/rpc-tests/wallet.py
src/rpc/blockchain.cpp

instead of cast to uint256, just convert commitment to hex string using HexStr()
invalidateblock.py had incorrect python syntax, it now passes

fixed gettxout rpc bug + invalidateblock.py syntax

---

src/chainparams.cpp
src/chainparams.h
src/qt/paymentserver.cpp

elementsd does not start on MacOS because of LOCK(cs_args) failuer when setting CChainParams::supportedChains.
the type of supportedChains is simple map (key/string, value/uint256), but its value were never used.
so change its type to 'vectorstd::string' instead of.

elementsd does not start on MacOS

---

src/wallet/rpcwallet.cpp

vin may always represents as numeric in rcp wallet(asset) command response.
but current implementation is following.
rpc command|response|help text
-|-|-
issueasset | string | (not descripted)
reissueasset | numeric | (not descripted)
listissuances | numeric | numeric

change type of vin to numeric in issueasset response.

---

src/chainparams.cpp
src/chainparams.h

Remove unneeded code.
Using Bitcoin genesis mainnet hash for pegged-bitcoin asset id was a
mistake in the first place, anyway.

Remove CChainParams::bitcoinID

---

src/wallet/rpcwallet.cpp

- command line
add assetlabel 
- arguments
change 'ALL ACCOUNT ARGUMENTS' to 'ALL OTHER ARGUMENTS'
- examples
specify asset label instead of DEPRECATED pattern

Fix help text in wallet/rpcwallet.cpp

---

src/wallet/rpcwallet.cpp

nAmount and nTokens never be negative value because AmountFromValue throws JSONRPCError if its argument holds negative value.

Remove redundant code (issueasset)

---

src/rpc/rawtransaction.cpp

Previously these values were used to explicitly calculate the fee. Since this construction was more brittle to advanced use-cases with multiple fees/actors, explicit fee outputs are now added, therefore this is now unneeded. 
TODO is to remove all the passed nValue/amount arguments, but no hurry since they are simply ignored.
Solves https://github.com/ElementsProject/elements/issues/180

Remove nValue/amount arguments from createrawtransaction

---

src/chainparams.cpp

Eliminates collision with Liquid address type.
Resulting prefix makes addresses start with "X".

change base58 prefix for script addresses

---

src/qt/test/rpcnestedtests.cpp

Stray unit test failing for branch. QT isn't supported regardless.

Disable QT test with hardcoded block hash values

---

qa/rpc-tests/p2p-fullblocktest.py
src/validation.cpp

The error message indicates that the outputs exceed the inputs. In reality, at least for blinded transactions, the error will also appear if the in exceeds the out, i.e. this error appears for all transactions where inputs do not sum up to outputs.

bad-txns-in-belowout -> bad-txns-in-ne-out

---

src/rpc/rawtransaction.cpp

[trivial] remove unused variable "amount" in rawtransaction.cppthe keyword "amount" was changed to "value" and is handled earlier if the output value is explicit. the "amount" variable was unused and currently is not necessary.

[trivial] remove unused variable "amount" in rawtransaction.cpp

---

src/miner.cpp

We have no centralization concerns, and mempool will still enforce minimums. This simply allows the miner to clear out the mempool as fast as possible based on feerate rather than wait for transactions to hit a minimum priority amount.

Miner selects any feerate no matter how small

---

qa/rpc-tests/confidential_transactions.py
src/wallet/wallet.cpp

Another dumb fundraw bug due to no test.
Transaction ended up missing things outside of the witness vector, like explicit fees.

fundrawtransaction needs to push back all outputs

---

qa/rpc-tests/confidential_transactions.py
qa/rpc-tests/receivedby.py
src/wallet/rpcwallet.cpp

Even if it receive multiple assets at the same address, listreceivedbyaddress ignores the asset type and sums it. listreceivedbyaccount and getreceivedbyaccount does same behavior too.
I think, like gettreceivedbyaddress, to sum amounts for each asset is better.

fix listreceivedbyaddress to sum amounts for each asset.

---

src/chainparams.cpp
src/init.cpp

The first part of https://github.com/ElementsProject/elements/pull/114 rebased to 0.14.
Since the whole thing isn't getting the review I thought it would be good to separate it.

HF: Genesis block includes fedpegscript and signblockscript

---

qa/rpc-tests/pegging.py
src/validation.cpp

This PR also includes a change which changes free relay to only work for withdrawlock spends, since those cannot include a fee, and removes the rate limiting. Pegging transactions are already rate-limited by Bitcoin fees on the mainchain, and miners will select higher-fee transactions, so DoS is unlikely.

Fix claimpegins from mempool locks

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/smartfees.py

Following fixes make "./qa/pull-tester/rpc-tests.py -extended" to normal termination.
- rpcbind_test.py
- fix invalid indentation.
- test_framework/util.py
- stop_nodes() accept NoneType. (rpcbind.py and smartfees.py call stop_nodes with no nodes because  their setup_network() does not start any nodes and actually does not test.)

fix rpc-tests to avoid illegal termination.

---

qa/rpc-tests/confidential_transactions.py
src/rpc/rawtransaction.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

This was causing segfault when funding multiple assets: https://github.com/ElementsProject/elements/issues/223
(upstream they are simply no longer copyable which should avoid things like this in future)

FundTransaction should avoid copying CReserveKeys

---

src/primitives/transaction.cpp

clear the vchCommitment vector first, otherwise you'll end up appending to the end of what was already in it instead of replacing it

fix SetToAsset bug where vchCommitment wasn't cleared before writing

---

contrib/assets_tutorial/assets_tutorial.py

Details won't show otherwise.
Thanks to @udiWertheimer for pointing this out.

python tutorial: gettransaction needs optional include_watchonly arg

---

src/primitives/transaction.h

Just some code clean up. The CAsset `asset` was used.

remove unnecessary code in IsFee() method

---

contrib/assets_tutorial/assets_tutorial.py
contrib/assets_tutorial/assets_tutorial.sh
src/amount.h
src/assetsdir.cpp
src/bench/coin_selection.cpp
src/bitcoin-tx.cpp
src/chainparams.cpp
src/consensus/params.h
src/init.cpp
src/policy/policy.h
src/qt/coincontroldialog.cpp
src/qt/paymentserver.cpp
src/qt/transactiondesc.cpp
src/qt/transactionrecord.cpp
src/qt/walletmodel.cpp
src/test/assetsdir_tests.cpp
src/test/lockedutxo_tests.cpp
src/test/sighash_tests.cpp
src/test/transaction_tests.cpp
src/test/txvalidationcache_tests.cpp
src/validation.cpp
src/wallet/rpcwallet.cpp

This makes each chain have its own pegged asset type that's based on the parent chain genesis hash. (this doesn't deal with BCH type spinoffs, clearly)
This sets the stage for giving proof that bitcoin is a "true" asset in and ASP proof that requires showing the pre-image.

Replace static BITCOINID with asset-derivation style generation

---

qa/rpc-tests/listtransactions.py
qa/rpc-tests/p2p-compactblocks.py
qa/rpc-tests/test_framework/blocktools.py
qa/rpc-tests/test_framework/mininode.py
src/primitives/transaction.h

and towards re-enabling rpc tests. This patch introduces ``CProof``, ``CTxOutValue``, ``CTxOutAsset`` and ``CTxOutNonce`` to mininode.py. It also adds some debug output to the main node that was helpful in trouble-shooting the interaction between mininode.py and the main node.
This patch is a step in the direction of having mininode be compatible with elements. it does not bring it nor the tests all the way there to pass.

work towards bringing mininode.py up to date with the main node

---

src/core_memusage.h

~~Also fixed comment in memusage.h~~

include the CTxWitness structure in memory usage accounting

---

src/validation.cpp

Leftover from previous secp API.

CSurjectionCheck copies vector instead of swapping

---

doc/man/bitcoin-qt.1
doc/man/bitcoind.1
src/init.cpp
src/validation.cpp
src/validation.h

~~Is this doing anything beyond killing death code?~~
Always allow mempool replacement.

p2p: Remove -mempoolreplacement

---

src/consensus/merkle.cpp
src/consensus/merkle.h

Turns out the path calculation code, as written, did not work. Additionally, doing the position -> path calculation at validation time is both wasteful and introduces a source of malleability. Thankfully none of this code is used anywhere yet.

f 'Add fast Merkle branch functions.'

---

contrib/devtools/check-doc.py
src/chainparams.cpp
src/chainparams.h
src/script/ismine.cpp

Spending op_true outputs has more to do with the wallet than with the chain. Perhaps this options should be per wallet in the multiwallet future?
Alternatively we can make it a field in CChainParams, but ```Params().NetworkIDString() == CHAINPARAMS_REGTEST``` defeats the whole point of having chainparams IMO.

Chainparams: decouple anyonecanspend are mine from regtest

---

qa/pull-tester/rpc-tests.py

This is the only test that checks mininode serialization, and runs efficiently. This will help catch errors due to changes to serialization.

make replace-by-fee.py a standard functional test

---

src/rpc/misc.cpp

As in #270, ```Params().NetworkIDString() == CHAINPARAMS_REGTEST``` defeats the whole point of having chainparams IMO.
Note getinfo gets removed upstream and getblockchaininfo and getmininginfo already do this.

RPC: getinfo: Replace testnet with more generic chain

---

qa/rpc-tests/replace-by-fee.py
src/validation.cpp

We can remove this independently of the removal on the wallet safely. We will break elements expecting the opt-in sequences to mean anything, but this is just a bad assumption.
EDIT: Rebased on top of #248

p2p: Remove opt-in part of RBF

---

src/chainparams.cpp
src/chainparamsbase.cpp
src/chainparamsbase.h
src/rpc/protocol.cpp

CHAINPARAMS_OLD_MAIN is meant to be used only for specific tests depending on base58, not as default for all unittests through CBaseChainParams::MAIN.
But that's not the reality, more tests are currenly dependent on CBaseChainParams::MAIN being equal to  CHAINPARAMS_OLD_MAIN or CHAINPARAMS_ELEMENTS 
So removing the constant CHAINPARAMS_ELEMENTS is moving forwards.
Also:
Dependencies:
~~- [ ] QA: Chainparams: Run functional tests with custom chain #274~~

Remove CHAINPARAMS_ELEMENTS 

---

src/wallet/rpcwallet.cpp

listunspent returns all asset types, and "*" is an invalid argument. This old text reflected older behavior.

fix help text for listunspent asset filter

---

src/callrpc.cpp

In the help message and the description of the [project site](https://www.elementsproject.org/sidechains/creating-your-own.html), the argument name which specify the host of the mainchain is `-mainchainrpchost`, but in the implementation it is `-mainchainhost`.
So change it from `-mainchainhost` to `-mainchainrpchost`.

Fix mainchain host arg name from mainchainhost to mainchainrpchost

---

src/callrpc.cpp

Is checking for own rpc password being set, rather than the mainchain one when appropriate.

callrpc: Check correct mainchainrpc field

---

src/policy/policy.cpp

Currently if it encounters something like an OP_RETURN output, then hits a fee output, it will count another OP_RETURN output.
We may want to completely relax the OP_RETURN requirement, since we make those outputs for blinder-balancing as well.

fix standardness check ordering of scriptpubkey

---

src/txmempool.cpp

Otherwise they will float in mempool, possibly triggering asserts on block creation.

remove orphaned descendents of peg-ins on block receive

---

src/policy/policy.cpp
src/rpc/client.cpp
src/rpc/mining.cpp

Useful to make sure majority of blocksigners are required to have peers accept non-standard blocks, rather than just a single blocksigner.
Will add a test.

testproposedblock option to reject non-standard block

---

src/chainparams.cpp

Dependencies:
~~- [ ] QA: Chainparams: Run functional tests with custom chain #274~~
~~- [ ] Chainparams: Remove CRegTestParams and use CCustomParams instead #263~~
~~- [ ] RPC: getinfo: Replace testnet with more generic chain #271~~
~~- [ ] Chainparams: Every chain should have a name #307~~

Chainparams: Remove CElementsParams

---

contrib/devtools/check-doc.py
src/chainparams.cpp
src/chainparams.h
src/chainparamsbase.cpp
src/chainparamsbase.h

Any class extending CChainParams directly should be fine.
Any class extending CRegTestParams should be fine, just extend CCustomParams instead (or just use the custom params if that's enough for your chain).
Dependencies:
~~- [ ] Chainparams: Every chain should have a name #307~~

Chainparams: Unify CRegTestParams and CCustomParams

---

qa/rpc-tests/pegging.py
src/wallet/rpcwallet.cpp

Test sniped from @jonasnick 
this will only work for p2wpkh v0, so test should catch regressions that underpay

correctly account for witness data in peg-in fee calc, add test

---

contrib/assets_tutorial/assets_tutorial.sh

sendtomainaddress was replaced with sendtomainchain.
I didn't test it following the tutorial.

Tutorial: Use sendtomainchain

---

src/policy/policy.cpp
src/policy/policy.h
src/rpc/mining.cpp
src/validation.cpp

resolves https://github.com/ElementsProject/elements/issues/315 and another issue where coinbase claiming dust fees becomes rejected

fix testproposedblock standardness issues

---

src/validation.cpp

pblock is nullptr in those cases
Follow-on PRs will introduce a way of inducing these failures more frequently for testing purposes.

fix segfault when block from disk has pegin failure

---

src/validation.cpp
src/validation.h
src/wallet/rpcwallet.cpp

previous claimpegin logic was simply wrong(if user isn't validating peg-in depth, it silently squashes other issues), and this is more modular.

simplify non-depth peg-in validity checking

---

qa/rpc-tests/pegging.py

tests that blocks are only temporarily rejected, and recovery happens once connection is restored

add peg test for bitcoind temporarily being down during peg validation

---

qa/rpc-tests/pegging.py

Without this commit pegging.py fails on my machine more than 50% of the cases.

Fix timing for bitcoin shutdown in pegging.py

---

qa/rpc-tests/pegging.py
src/rpc/rawtransaction.cpp
src/script/script.cpp
src/script/script.h

This is to give more rich info on RPC calls that return info about scriptPubKey's in outputs if the scriptPubKey is a pegout.
~~Needs tests.~~

RPC: If a scriptPubKey is a pegout, show pegout info too

---

src/rpc/blockchain.cpp
src/rpc/client.cpp

backport of e3c9f2ddb1e49f719cc1f3f7cc2a98626bee4364
"Use a verbosity instead of two verbose parameters
Verbose is changed to an int. This can have values from 0-2 for each level of verbosity.
Verbosity level 2 has transaction details displayed in the results."

[backport] 'Use a verbosity instead of two verbose parameters'

---

src/chainparamsbase.cpp

Instead of having petname the name it is directly taken from -chain=<petname>.

Correct chain selection help

---

contrib/assets_tutorial/elements1.conf
contrib/assets_tutorial/elements2.conf
qa/rpc-tests/pegging.py
qa/rpc-tests/test_framework/util.py
src/chainparams.cpp
src/chainparams.h
src/init.cpp
src/test/test_bitcoin.cpp

In most cases you don't want them.

Default custom chains to no free coins

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/signed_blockchain.py
src/pow.cpp
src/script/interpreter.cpp
src/script/interpreter.h

Previous evaluation allows all sorts of witness malleability, which could be a DoS concern.

Make block solutions more strictly validated

---

src/chainparams.cpp
src/init.cpp

Default is testnet, as before.

allow setting parent chain address prefix in configuration file

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/blockchain.py

Since https://github.com/ElementsProject/elements/pull/344 works locally but fails in weird ways in travis, let's just reactivate and improve the test first for now until we understand what's happening on #344 .
More tests shouldn't hurt and if merged should also reduce #344's diff.

QA: Reactivate and improve rpc_blockchain tests

---

qa/rpc-tests/blockchain.py
src/pow.cpp
src/pow.h
src/rpc/blockchain.cpp
src/rpc/mining.cpp
src/rpc/misc.cpp
src/rpc/server.h

Bigger refactor than I initially thought.
But basically still cleaning up pow stuff we don't need, and including a few new blocksign-related fields that replace those and document them. 
Doesn't come with tests, but if it's not only rpc, then nack, please.
Dependencies:
~~- [ ] RPC: Stop providing useless fake pow data #366~~

RPC: Signblock: Support signblock info on rpc/blockchain

---

qa/rpc-tests/pegging.py
src/rpc/misc.cpp

This is a port of the changes made in liquid-deamon to add tweakfedpegscript in rpc/misc.cpp.

Port tweakfedpegscript from liquid-deamon

---

src/validation.cpp
src/validation.h

This should not change behavior in any way.
Separated out of https://github.com/ElementsProject/elements/pull/362

Refactor: Validation: Make parts of IsValidPeginWitness templated

---

Makefile.am

Remaining of cache may interfere the expected execution of the ```rpc-test.py```
Recently, it occurred after pull #355 (and ```make clean``` et al.) to my enviroment.
This patch make ```make clean-local``` remove the ```qa/cache``` and ```__pycache__``` folders.
cherry-picking form: https://github.com/bitcoin/bitcoin/pull/11842

[build] Add missing stuff to clean-local

---

src/chainparams.cpp
src/consensus/params.h
src/miner.cpp
src/pow.cpp
src/pow.h
src/rpc/blockchain.cpp
src/rpc/mining.cpp
src/wallet/rpcwallet.cpp

Since the scriptPubKey for signing blocks never changes, there's no
point reading repeating it from every block header.
Subset of https://github.com/ElementsProject/elements/pull/313

NO-HF: Move block.proof.challenge to Consensus::Params::signblockscript

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/default_asset_name.py
qa/rpc-tests/initial_reissuance_token.py
src/assetsdir.cpp
src/assetsdir.h
src/chainparams.cpp
src/chainparams.h
src/global/common.cpp
src/global/common.h
src/init.cpp
src/test/assetsdir_tests.cpp

Changes to enable you to use Elements as a stand alone blockchain by setting new params:
-initialreissuancetokens
-defaultpeggedassetname
NOTES:
In order to use reissuance tokens for the default asset they must be moved from anyone-can-spend first. 
When using defaultpeggedassetname as a parameter: sendtoaddress, sendmany requires the asset name parameter passing in in order to use your default asset and not 'bitcoin'. Could change this at a later date as part of more serious decoupling, but might require a lot of knock on changes.
EXAMPLE USE:
(based on https://github.com/ElementsProject/elements/blob/elements-0.14.1/contrib/assets_tutorial/assets_tutorial.sh)
`
ASSET="mynewasset"
trap read debug
e1-dae -initialreissuancetokens=200000000 -defaultpeggedassetname=$ASSET
e2-dae …

Enable setting of default asset name and initial reissuance token count

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/assetdir.py
src/wallet/rpcwallet.cpp

Addresses Issue #387 
This enables you to pass the label of an asset into listissuances. Previously you had to use a hex.
Added new test that covers assetdir in general and this PR.

Add ability to use listissuance with label as param. Plus tests.

---

qa/rpc-tests/zmq_test.py

When run in a docker Ubuntu instance under Centos 7, the script `qa/rpc-tests/zmq_test.py` will typically hang indefinitely (even though it has reported a successful -- albeit mostly stubbed-out -- completion). Using gdb to debug the [core file manually generated from the] associated python instance reveals that the main thread is waiting for a call to zmq_ctx_term() to end -- a scenario similar to  that described in https://github.com/zeromq/libzmq/issues/2586
This change adds the workaround described in the issue (namely to explicitly call `self.zmqContext.destroy(linger=0)` after the process is finished with zmq).
Note: the workaround is otherwise innocuous for any environment not experiencing a hang.

Tests: Explicitly destroy zmq object when exiting after not actually using it

---

src/chainparamsbase.cpp
src/init.cpp

Most important fix is being explicit that the cookie file is being searched for under "regtest" by default.

mainchainrpc* description fixes

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/feature_fedpeg.py
qa/rpc-tests/test_framework/util.py
src/chainparams.cpp
src/consensus/params.h
src/init.cpp
src/pow.cpp
src/pow.h
src/rpc/blockchain.cpp
src/validation.cpp
src/validation.h
src/wallet/rpcwallet.cpp

Fix https://github.com/ElementsProject/elements/issues/360 (doesn't really fix it as noted in https://github.com/ElementsProject/elements/pull/362#issuecomment-406085649 , but it is still useful for testing)
Dependencies:

2WP: Allow other elements chains as parent chains for pegs

---

src/test/test_bitcoin.cpp
src/test/txvalidationcache_tests.cpp

Set policyAsset for all core c++ unit tests #408 
src/test/txvalidationcache_tests.cpp was failing with memory access violation somewhere in block creation. I believe it's because now that mempool entry fee is correctly set, the fact that the fee output was larger than the non-fee one was causing an issue. I haven't been able to track this down exactly though. Please let me know if you have some idea about this and if the change makes sense.

Set policyAsset for core unit tests

---

qa/rpc-tests/pruning.py
src/callrpc.cpp
src/callrpc.h
src/merkleblock.h
src/primitives/bitcoin/merkleblock.h
src/rpc/blockchain.cpp
src/validation.cpp
src/validation.h
src/wallet/rpcwallet.cpp

Use the getblockheader RPC from Bitcoin Core to verify if the number of
transactions mentioned in the SPV proof matches the number for the
block known by the Core daemon.
Inspired by https://github.com/bitcoin/bitcoin/commit/6b9dc8ceaed597d9c539ba6b09c171b258b66ca3
Partially fixes https://github.com/ElementsProject/elements/issues/369

2WP: Verify number of transactions in SPV proof

---

src/validation.cpp

[backport] Fix crash bug with duplicate inputs within a transaction

---

qa/rpc-tests/feature_fedpeg.py

...which is redundant and inferior to the one in the test framework.
We needed to re-implement it to avoid pegging.py depending on the freamework, but we don't need it anymore.

QA: feature_fedpeg.py: Remove re-implementation of sync_all

---

qa/rpc-tests/feature_fedpeg.py
qa/rpc-tests/test_framework/util.py

Resolves https://github.com/ElementsProject/elements/issues/420

feature_fedpeg.py bitcoind parent2 uses rpc cookie auth

---

qa/rpc-tests/feature_fedpeg.py
src/init.cpp
src/validation.cpp

Resolves https://github.com/ElementsProject/elements/issues/424
We ensure that peg-in invalid blocks are marked as "bad", and allow the re-checking logic to actually re-check instead of immediately re-evaluating the block.
Take locks and check for existence of keys in mapBlockIndex, when appropriate.
Also actually includes a valid test for it by making sure it takes more than a few seconds to fix itself but doesn't hit test timeout.

peg-in re-checking cleanup and fixes

---

src/Makefile.am
src/chainparams.cpp
src/chainparams.h
src/chainparamsbase.cpp
src/init.cpp
src/rpc/blockchain.cpp
src/rpc/mining.cpp
src/test/test_bitcoin.cpp
src/versionbits.cpp
src/versionbits.h
src/versionbitsinfo.cpp
src/versionbitsinfo.h

This is a backport of https://github.com/bitcoin/bitcoin/pull/13311 since it's already merged, merging this in elements-0.17 should at least make the next rebase slightly easier. And since we're heavily touching chainparams in elements, I think it's a good thing.

[0.17] Don't edit Chainparams after initialization

---

test/functional/example_test.py

Fix this useful test in -extended.
IMO should be backported to bitcoin/0.17, but I'm not sure if it's wanted there.

[0.17] Test: Fix example_test.py

---

src/chainparams.cpp
src/chainparamsbase.cpp
src/consensus/params.h
src/validation.cpp
test/functional/mandatory_coinbase.py

[0.17] Mandatory coinbase feature

---

src/chainparams.cpp
src/chainparamsbase.cpp
src/consensus/params.h
src/test/main_tests.cpp
src/validation.cpp
test/functional/feature_block_subsidy.py
test/functional/test_framework/util.py
test/functional/test_runner.py

Previously we just set this to 0 and continued, this allows tests to otherwise pass up until this point.

[0.17] add block subsidy argument to allow different/non-inflation chains

---

.travis.yml

pin flake8 version to avoid breaking compatibilities

---

src/chainparams.cpp
src/chainparamsbase.cpp
src/consensus/params.h
src/rpc/rawtransaction.cpp
src/validation.cpp
test/functional/feature_connect_coinbase.py
test/functional/test_framework/util.py
test/functional/test_runner.py

[0.17] Connect gen block tx to db, don't validate gen block

---

README.md

Changed links to point to new website content and removed references to old pages.
Includes some minor text changes to the intro and summary to remove suggestion its intended primary use is as a Bitcoin testbed.
Removed links to Schnorr, SW as these do not have pages on the new site (can add if needed).

Updated README links to point to new elementsproject.org content.

---

contrib/assets_tutorial/bitcoin.conf

Core v0.17 now handles config file settings differently and loads the existing config settings as mainnet and not regtest. This means our e1 and e2 nodes in the tutorial can't connect. 
This PR makes the bitcoin.conf file compatible with both formats. Without this change the tutorial code fails if you are using bitcoind v0.17.0.0.
REF: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.17.0.md
If the following options are not in a section, they will only apply to mainnet:
`addnode=`, `connect=`, `port=`, `bind=`, `rpcport=`, `rpcbind=` and `wallet=`.
The options to choose a network (`regtest=` and `testnet=`) must be specified
outside of sections.
Tested with bitcoind v0.16.2.0 and v0.17.0.0

Changed tutorial bitcoin config file to work with new core v0.17 format

---

test/functional/test_runner.py

This is what upstream master has, and helps not hide issues more.

[0.17] move most extended tests to normal

---

qa/rpc-tests/confidential_transactions.py
src/rpc/rawtransaction.cpp

fixes https://github.com/ElementsProject/elements/issues/459

fix endianness of getrawtransaction issuance entropy, add basic test

---

src/chainparams.cpp
src/chainparams.h
src/init.cpp
src/script/ismine.cpp
src/script/sign.cpp
src/script/standard.cpp
src/script/standard.h
test/bitcoin_functional/functional/test_framework/util.py
test/functional/test_framework/util.py

This aids in testing and is used in https://github.com/ElementsProject/elements/pull/452 but is useful elsewhere too.

Add TX_TRUE output format, accept in wallet with `anyonecanspendaremine`

---

src/chainparamsbase.cpp
src/init.cpp
src/util.cpp
src/util.h

Attempt to group elements-specific -options together.

[0.17] Add OptionsCategory::ELEMENTS

---

qa/rpc-tests/feature_issuance.py
src/blind.cpp
src/rpc/client.cpp
src/rpc/misc.cpp
src/rpc/rawtransaction.cpp

Follows a similar transaction creation flow as #474 . Tests demonstrate a multi-sig spend of a reissuance token to issue additional assets.
Also includes a number of fixes I discovered along the way.

rawreissuance rpc

---

src/chainparams.cpp
test/bitcoin_functional/functional/test_framework/util.py
test/functional/feature_block_v4.py
test/functional/test_framework/util.py
test/functional/test_runner.py

By setting the BIPXX consensus fields to `0` we allow them to be enforced from genesis block by default.
This means blocks will be required to be at least version 4 by default.
Also adds tests.
Todo for later: `BIP34_IMPLIES_BIP30_LIMIT` right now means all chains will slow down validation at height `1983702`. We should prod upstream to do something smarter, or allow this to be set as an argument.

[0.17] Block v4 mandatory

---

src/init.cpp
src/protocol.h
src/qt/guiutil.cpp
src/validation.cpp
src/validation.h
src/wallet/wallet.h
test/bitcoin_functional/functional/test_framework/util.py
test/functional/test_framework/util.py

Setting `-mempoolreplacement=fee,-optin` will cause the node to honor any RBF replacements even if they had the opt-out flags set.
This also sets the default for the wallet to create bip125-signaling transactions.

[0.17] Full RBF support

---

src/blind.cpp

As discussed in #485, src/blind.cpp should have a standard license header.

add standard license header to src/blind.cpp

---

src/blind.cpp
src/test/blind_tests.cpp

if nNonce.vchCommitment contains invalid key of correct length,
IsValid() check will pass, but then assertion will be hit
when secp256k1_ec_pubkey_parse() is called on it inside CKey::ECDH().
Therefore, the check should be done with IsFullyValid()
reported in #488

Fix UnblindConfidentialPair: use IsFullyValid() for ephemeral_key

---

src/secp256k1/.travis.yml
src/secp256k1/src/modules/rangeproof/tests_impl.h

Type mismatch may have been causing rangeproof verification failure in secp unit tests on 32 bit systems.
The rangeproof unit tests also run far too long, so iterations are cut down to avoid a 10 minute Travis timeout.

secp-zkp update to fix a couple Travis issues

---

src/blind.cpp

Because explicit conversion of arbitrarily large unsigned values
to signed values of the same bit width is implementation defined
until c++20, better check against MAX_MONEY with unsigned comparison.

check amount against MAX_MONEY with unsigned comparison

---

.travis.yml
src/chainparams.cpp
src/chainparamsbase.cpp
test/bitcoin_functional/functional/test_framework/util.py
test/functional/feature_block_v4.py
test/functional/test_framework/util.py

Guts the test for elements mode, can add back later if worked on.

[0.17] Activate CSV from genesis block for custom chains

---

qa/rpc-tests/confidential_transactions.py
src/wallet/rpcwallet.cpp

Something we should have implemented a long time ago. This lets auditors not import transactions into the wallet to deblind them.
Future extensions could allow ephemeral "import" of blinding keys as to not change wallet state.

add RPC to deblind transactionwith blinding keys in wallet

---

src/validation.cpp

Transaction serialization requires that witness-empty transactions have empty witness vectors for inputs and outputs. While fixing the OOB access in `VerifyAmounts` we accidentally softforked out the ability to have issuances in transactions with no other witness data. In real-life usage this is fairly unlikely, since any blinding, any segwit signatures, and any peg-in data make this not true.

Add comment on witness-null issuance transactions' invalidity

---

src/validation.cpp

Based on #515.
Backport of https://github.com/Blockstream/liquid/pull/8

[0.17] backport "Validation: stop logging fake pow data"

---

src/wallet/rpcwallet.cpp

These aid in integration testing allowing the caller to sends funds wherever.

[0.17] Manual pak RPC calls

---

src/interfaces/node.cpp
src/rpc/blockchain.cpp
src/validation.cpp
src/validation.h
src/wallet/wallet.cpp
test/functional/feature_progress.py
test/functional/test_runner.py

Based on https://github.com/ElementsProject/elements/pull/515
Reimplementation of https://github.com/Blockstream/liquid/pull/6

[0.17] Fix progress reporting issue

---

.travis.yml

secp-zkp unit tests takes over 10 minutes, which triggers a Travis timeout.
Until we fix it upstream it's probably better to know it compiles and maybe passes functional tests.
DEBUG=1 builds are also timing out, so split up concerns into two different runs.

Let's try to have more builds complete within allotted time

---

.travis.yml

Times out currently at QT build, really we just use this as a compile test for wallet ifdef macro junk.

[0.17] Fix no wallet build

---

src/rpc/protocol.cpp
src/test/util_tests.cpp
src/util.cpp
test/util/data/bitcoin-util-test.json

Cookie defaults looking in `regtest` directory currently.

[0.17] Default to elementsregtest, when syncing liquid, find cookie

---

src/primitives/transaction.h

backport of https://github.com/ElementsProject/elements/pull/402 which is a backport of upstream

[0.17] Disallow extended encoding for non-witness transactions

---

.travis.yml
.travis/test_06_script.sh
src/chainparams.cpp
test/functional/feature_fedpeg.py
test/functional/test_framework/test_framework.py
test/functional/test_framework/test_node.py

Add Travis fedpeg test with downloaded bitcoind

---

.travis.yml
test/functional/feature_assetsdir.py
test/functional/feature_block_subsidy.py
test/functional/feature_block_v4.py
test/functional/feature_blocksign.py
test/functional/feature_confidential_transactions.py
test/functional/feature_connect_coinbase.py
test/functional/feature_default_asset_name.py
test/functional/feature_fedpeg.py
test/functional/feature_initial_reissuance_token.py
test/functional/feature_issuance.py
test/functional/feature_mandatory_coinbase.py
test/functional/feature_pak.py
test/functional/feature_progress.py
test/functional/feature_txwitness.py
test/functional/rpc_tweakfedpeg.py

We removed QT building which seemed to help, maybe we can reintroduce functional tests.

Re-enable no wallet functional tests

---

src/chain.h
src/txdb.cpp

We diverged from the 0.14 codebase, fix included here as well as performance speedup on initial load.
In 0.14 we did no signature checking at all, but the signature checks were what alerted me to the incompatibility, so I opted to preserve some of that as sanity check.

Blockindex compatibility fix, startup speedup

---

qa/rpc-tests/feature_issuance.py

Issue discovered during elements-0.17 rebase.

Actually test multisig rawreissuance

---

src/blind.cpp

The size of surjectionTargets and targetAssetGenerator vectors was calculated as tx.vin.size()*3, based on the fact that for each input there might also be up to 2 issuance pseudo-inputs, but did not take into account that the number of auxiliary generators may exceed the number of inputs. This fixes the size calculations by taking into account auxiliary generators supplied beyond vin size.

fix vector length calculation for targets in BlindTransaction

---

qa/rpc-tests/confidential_transactions.py
qa/rpc-tests/test_framework/mininode.py

This PR adds fixes for witness serialization/deseralization in qa/rpc-tests/test_framework/mininode.py
and extends multisig tests in qa/rpc-tests/confidential_transactions.py with partial blinding tests

Add partial blinding test to qa/rpc-tests

---

src/pegins.cpp
src/wallet/rpcwallet.cpp
test/functional/feature_fedpeg.py

resolves https://github.com/ElementsProject/elements/issues/14
Technically a softfork but not really since the elements chain would eventually become valid anyways.

Enforce coinbase maturity on bitcoin peg-ins

---

src/rpc/client.cpp
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
test/functional/feature_confidential_transactions.py

resolves https://github.com/ElementsProject/elements/issues/547
Previous API was improperly overloading the specific blinding key calls, and incorrectly on top of that.
Instead implement `importmasterblindingkey` and `dumpmasterblindingkey` and check that `dumpwallet` details are enough to recover same blinded wallet addresses.

Make new actually working master blinding calls, test

---

test/functional/feature_confidential_transactions.py

forward port of https://github.com/ElementsProject/elements/pull/510
@dgpv

add code to test partial blinding functionality to qa/rpc-tests

---

src/rpc/rawtransaction.cpp
test/functional/feature_confidential_transactions.py

Allows a no-data burn of any given asset using the raw interface to support multi-sig burn when `destroyamount` will not suffice.
Resolves https://github.com/ElementsProject/elements/issues/557

Create burn argument for createrawtransaction

---

src/wallet/rpcwallet.cpp

Cherry-pick of https://github.com/ElementsProject/elements/pull/231.

Don't blind with blinding factors that aren't ours

---

test/functional/feature_fedpeg.py

Problem is this assert is hard to hit in practice, only Travis seems to.
We should not be relying on the mempool consistency checks to make sure bad blocks don't get accepted during parent chain RPC failure so let's just have the node continue and check behavior we expect.

Turn off mempool consistency check in fedpeg test to avoid assert

---

src/chainparams.cpp
src/wallet/rpcwallet.cpp
test/bitcoin_functional/functional/test_framework/util.py
test/functional/feature_fedpeg.py
test/functional/test_framework/util.py

Also chose `ert` as bech32 hrp, just to make it distinct.
Clustered the various address parameters for ease of the reader.
resolves https://github.com/ElementsProject/elements/issues/567

Adapt Elements default adress prefix bytes to elements-0.14 style

---

src/key_io.cpp
src/rpc/misc.cpp
test/functional/feature_fedpeg.py
test/functional/feature_pak.py

Added more utility to `validateaddress` for parent addresses by returning an additional object `parent_address_info`, then used it to enhance various tests.

Some more standard pegout testing

---

.travis.yml
configure.ac
contrib/gitian-descriptors/gitian-linux.yml
contrib/gitian-descriptors/gitian-liquid-linux.yml
contrib/gitian-descriptors/gitian-liquid-osx.yml
contrib/gitian-descriptors/gitian-liquid-win.yml
contrib/gitian-descriptors/gitian-osx.yml
contrib/gitian-descriptors/gitian-win.yml
src/interfaces/wallet.cpp
src/qt/guiconstants.h
src/qt/guiutil.cpp
src/qt/transactiondesc.cpp
src/qt/walletmodel.cpp
src/test/util_tests.cpp
src/util.cpp

The only behavior it modifies is that the default chain becomes `liquidv1`. Also added a Travis test for coverage and adapted a unit test, and enabled this mode for gitian descriptors.

configure option --enable-liquid for default liquidv1 chain

---

src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
test/functional/feature_confidential_transactions.py

Currently any fundrawtransaction call will result in unblinded change output. Automated flow isn't effected by this bug.

CreateTransaction: Place blinding pubkey into nNonce in case of fundraw

---

src/chainparams.cpp

liquidv1 has a testdummy deployment like other common chains, sync this up.

Add testdummy deployment for versionbits to squash warnings

---

src/wallet/rpcwallet.cpp
test/functional/feature_fedpeg.py

resolves https://github.com/ElementsProject/elements/issues/599

refactor getpeginaddress to not call getnewaddress RPC

---

src/init.cpp
src/validation.cpp

First, only start scheduling checks if the initial check on load succeeds. This initial check is a sanity-check that makes sure all daemons are spun up and communicating correctly. Second, for the initial check only we want to spin-wait for the mainchaind to finish warming up, otherwise elementsd may fail rather than wait a couple seconds for bitcoind to start up, for instance, which can occur when automating the processes.
Previously we were spin-waiting for all instances of MainchainRPCCheck, which means if your bitcoind falls over mid-run for whatever reason and is in warmup state for a long time(say, updating UTXO db), these checks will pile up on each other, spamming your bitcoind with useless RPC calls. Post-init it's completely fine for the call to simply fail and try again in N …

Make MainchainRPCCheck a bit less aggressive

---

src/validation.cpp
src/wallet/rpcwallet.cpp
test/functional/feature_fedpeg.py

Fixes #612 and #613.
- prevents a double claim from entering mempool
- makes `claimpegin` throw an exception when trying to double claim a pegin
- check the last commit message on all the extra cases that are tested.

Improve double pegin claim behavior

---

src/rpc/rawtransaction.cpp
test/functional/rpc_psbt.py

We're not really supporting PSBT for Elements yet. The `rpc_psbt.py` integration test is disabled because of this; that's also why we didn't catch this. It's fixed upstream. 
I added an extra test to catch the error, but it's not actually executed.
@instagibbs, up to you to decide if it's worth having this patched right now. I cherry-picked that fix commit literally from the catchup PR I'm working on, so if we don't patch it here, it will get patched while catching up.

Fix default permitsigdata value not working on converttopsbt command

---

src/test/mempool_tests.cpp
src/test/policyestimator_tests.cpp
src/txmempool.cpp
src/txmempool.h
src/validation.cpp

Completely redundant since https://github.com/ElementsProject/elements/pull/260 when peg-in inputs have taken on deterministic prevouts, so normal mempool logic has taken over for accounting for double-spending peg-in proofs in the mempool.
resolves https://github.com/ElementsProject/elements/issues/624

kill useless mapPeginsSpentToTxid

---

src/outputtype.cpp
test/functional/feature_confidential_transactions.py

Alias "blech32" to "bech32" for address creation

---

src/primitives/pak.cpp
src/script/script.cpp

related to https://github.com/ElementsProject/elements/issues/598 , https://github.com/ElementsProject/elements/issues/596, https://github.com/ElementsProject/elements/pull/597
This does not affect consensus, but affects consumers of these parsing rules such as rust-elements.
cc @apoelstra @roconnor-blockstream

All peg-out related detection pushes should be <= OP_PUSHDATA4

---

src/wallet/rpcwallet.cpp

Enough people are running `-regtest` and getting confused as to why they cannot issue assets to make some checks worth it even though we don't intend people to run bitcoin mode at all.

Disallow issuance calls in bitcoin mode

---

src/wallet/rpcwallet.cpp

Cheaper peg-in witness for those with segwit transactions in Bitcoin.
resolves https://github.com/ElementsProject/elements/issues/628

have peg-in witness creation strip witness for space savings

---

src/rpc/rawtransaction.cpp

This matches the behavior of `issueasset`.
Resolves https://github.com/ElementsProject/elements/issues/643

rawissueasset: don't make explicit 0-value which gets blinded later

---

src/init.cpp

Also fix second->millisecond regression from 0.17

Move MainchainRPCCheck to its own schedule to avoid waiting for itself

---

src/interfaces/wallet.cpp
src/interfaces/wallet.h
src/qt/transactiondesc.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

[0.17 backport] Fixup some QT-only credit computing code 

---

src/init.cpp

[0.17 backport] Move MainchainRPCCheck to its own schedule to avoid waiting for itself

---

src/wallet/wallet.cpp

Backport of https://github.com/ElementsProject/elements/pull/660.

[0.17 backport] FundTransaction: mark all change keys as kept #660 

---

src/wallet/wallet.cpp

Regression from 0.14 due to internal API changes.
If a key has already been marked returned it's a nop.

FundTransaction: mark all change keys as kept

---

src/wallet/rpcwallet.cpp

Since this RPC call is likely the first place people are exposed to this UI quirk, explain it here.

Better explain the 8-decimal asset issuance.

---

src/consensus/tx_verify.cpp
src/validation.cpp

The non-depth check is very cheap, and could be made even cheaper in the future given the proper assumptions. Depth checks are only required for `CheckTxInputs`.

Do non-depth check for peg-in witness where possible

---

src/consensus/tx_verify.cpp
src/validation.cpp

[0.17 backport] Do non-depth check for peg-in witness where possible #664

---

src/blind.cpp
test/functional/feature_confidential_transactions.py

This prevents the assertion from crashing the node when an RPC user
enters invalid blinding factors.
Fixes #540.

Don't assert on user-inputed values

---

src/wallet/rpcdump.cpp

Before:
$ elements-cli help | grep importblindingkey
importblindingkey "address" "hexkey"
importblindingkey "hexkey"
$ elements-cli help | grep importmasterblindingkey
After:
$ elements-cli help | grep importblindingkey
importblindingkey "address" "hexkey"
$ elements-cli help | grep importmasterblindingkey
importmasterblindingkey "hexkey"

Fix importmasterblindingkey help

---

src/wallet/rpcwallet.cpp
test/functional/feature_confidential_transactions.py
test/functional/wallet_labels.py

The support of assetlabel parameter that was previously present left behind from elements-0.17 when #515 have been merged. 
I think it is still useful for these commands to support assetlabels.
This patch add assetlabel support to following RPC:
1. getreceivedbyaddress
Add the 3rd parameter as "assetlabel"
Print 'optional' explicitly in the help text.↲
2. getreceivedbylabel
Add the 3rd parameter as "assetlabel"
Print 'optional' explicitly in the help text.↲
3. gettransaction
Add the 3rd parameter as "assetlabel"
4. getbalance
Set the name of 4th parameter as "assetlabel".
Print 'optional' explicitly in the help text.↲
5. listreceivedbyaddress
Set the name of 5th parameter as "assetlabel".
Enable assetlabel selection to the result of amounts.
Print 'optional' explicitly in the help text.↲ …

[RPC]Add assetlabel support to some commands

---

src/primitives/transaction.h

This is not a consensus change, as "honest" serialization for size/txid purposes will not include these, and only the amounts fields are used in "balance" checking later.

Disallow issuance-stuffing in tx deserialization

---

src/test/util_tests.cpp
src/util/system.cpp

In general if people are running their own experimental chains they should do so by specifying `-chain=<whatever>` rather than relying on defaults. When none is given, most likely the user is trying to use `liquidv` anyways.

Change default chain to liquidv1

---

contrib/gitian-descriptors/gitian-linux.yml
contrib/gitian-descriptors/gitian-osx.yml
contrib/gitian-descriptors/gitian-win.yml

Makes the gitian output wrong otherwise:
```
Generating report
ec40c90d48ea38bb63cf1d36a0695810412ac3676e3359ad62e8ccf5273a0fcf  elements-0.17.0-aarch64-linux-gnu-debug.tar.gz
...
613418e96782c9e7cd5b9427e851a96575b1252fc14a0decad63d9b29bcd515a  src/elements-0.17.0.tar.gz
ba84ba37eb386b51492247edafa5f23c921cb81ca1a9eea06273d6aadc885f36  elements-linux-0.18-res.yml
```

Fix gitian descriptor major version for yml

---

src/wallet/rpcwallet.cpp
test/functional/feature_confidential_transactions.py

In #510 / #550 a requirement that the blinding commitments were equal in amount to the inputs was introduced. This requirement is correct for the final case, but not for partial transactions (e.g. where party 1 blinds their inputs before even handing the transaction over to party 2 to add theirs). In order to hide party 1's input amounts from party 2, blindrawtransaction must allow >= the inputs, since the commitments are shared beforehand (if not, the blinding fails; this may need further investigating).
This PR restores the functionality to allow blinding commitments more than or equal to the amount of inputs, which makes the confidential assets demo https://github.com/ElementsProject/confidential-assets-demo functional again.

[rpc]blindrawtransaction accepts more commitments

---

contrib/assets_tutorial/elements2.conf

I was confused to instructions in [Elements code tutorial](https://elementsproject.org/elements-code-tutorial/working-environment):
> `cp ~/elements/contrib/assets_tutorial/elements2.conf ~/elementsdir2/elements.conf`
But, in `~/elements/contrib/assets_tutorial/elements2.conf`, the network type is not specified at the beginning.
I got an error after `e2-cli`:
```
$ e2-cli getwalletinfo
error: Could not connect to the server 127.0.0.1:7041
Make sure the daemon server is running and that you are connecting to the correct RPC port.
```
because elements default network is liquid, the port is 7041, so if you don't point the correct chain, you wouldn't get correct info.
So I think the correct elements2.conf as below:
```
chain=elementsregtest
rpcuser=user2
rpcpassword=password2 …
```

fix config err

---

src/interfaces/wallet.cpp
src/qt/networkstyle.cpp

backport of https://github.com/ElementsProject/elements/pull/693

[0.18 backport]  Qt fixes post 18

---

src/rpc/server.cpp
src/wallet/rpcwallet.cpp
test/functional/feature_pak.py

backport of https://github.com/ElementsProject/elements/pull/696

[0.18 backport] sendtomainchain with pak and subtract fee from output fix

---

test/functional/feature_confidential_transactions.py
test/functional/test_framework/liquid_addr.py

I used the code from test/functional/test_framework/liquid_addr.py with the same length check adjustments in python-elementstx to decode Liquid's blech32 addresses, and it seems to be working fine.

fix len check in blech32 decode() in test framework

---

src/chainparams.cpp
src/consensus/params.h
src/pegins.cpp

A single field wasn't given a positive value which
meant it considers no peg-ins to be valid. This is something introduced by dynafed.
I put in a guess placeholder, the important part is that it's > 0.

Fix liquidv1 sync

---

src/chainparams.cpp
src/consensus/params.h
src/pegins.cpp

Backport of Fix liquidv1 sync #720

[0.18 backport] Fix liquidv1 sync #720

---

src/Makefile.test.include
src/test/dynafed_tests.cpp

I created these for having test vectors for rust-elements, but it makes sense to have them around so that we don't accidentally change them.

Add unit test for dynafed CalculateRoot methods

---

src/block_proof.cpp
src/hash.h
src/rpc/mining.cpp
src/script/generic.hpp
src/wallet/rpcwallet.cpp

It is not included in the signature hash. 
The sighash byte MUST be SIGHASH_ALL to avoid malleability.

[HF] Dynafed blocks must have sighash byte

---

contrib/assets_tutorial/assets_tutorial.py

Versions 0.18+ require a witnessScript argument for signblock unless the start arguments specify the ``con_dyna_deploy_start`` argument as ``0``.

Fix assets_tutorial.py signblock dynafed error

---

.travis.yml

This particular build is intended for bitcoin_functional tests only, and the unit tests are timing out consistently for some unrelated reason, so turn them off.

Don't run unit tests for compatibility run(which is a NOP)

---

src/psbt.h

https://github.com/bitcoin/bips/pull/849 (not yet merged) adds to BIP 174 proprietary types. This PR changes the PSBT types used in Elements to be in line with the proposed changes to the BIP/

Change Proprietary types to use the method specified in BIP 174

---

src/rpc/mining.cpp

This may help reduce the failures in `feature_blocksign.py` that seem to occur fairly often. It could be that the mempool is in an inconsistent state, which messed up compact block finalization.

Take mempool locks when doing compact block RPC calls touching mempool

---

src/rpc/mining.cpp

If you instantiate `InitData` with a non-empty mempool, it may find "missing transactions", fill them in, and then the missing transaction index vector is now faulty and fails.
All data is already available to finish the block(or not in case of collision), just use given data.
Fixes intermittent feature_blocksign.py failure.

Fix finalizecompactblock filling in more found txs from mempool

---

src/rpc/mining.cpp
test/functional/feature_blocksign.py

We were putting together the block wrong in a couple ways.
The order of the transactions matter when give as the "missing transactions" list. We're simply feeding it two lists of transactions that together should contain the full block. Also we should actually serialized the 2nd argument rather than the 1st, again.

finalizecompactblock: Fix it

---

.travis.yml
.travis/test_06_script_a.sh
.travis/test_06_script_b.sh
src/rpc/mining.cpp
test/functional/feature_blocksign.py
test/functional/feature_fedpeg.py

1) Don't run unit tests for compatibility run(redundant)
2) Disable functional tests for sanitizer runs which have been OOM for a while now
3) only use mempool sync in fedpeg test to avoid connection complexity, add a bunch of sync calls to avoid hanging validation failure corner cases
4) run functional tests exactly once
5) fix finalizecompactblock RPC

[0.18] Reduce Travis errors

---

src/rpc/mining.cpp

If someone transitions to a different block type, including something else op_true-ey but not exactly, `generatetoaddress` and ilk will complain without much recourse.

Give more descriptive error for non-WSH(OP_TRUE) block generation

---

src/net_processing.cpp
src/policy/feerate.h
src/policy/policy.h
src/test/test_bitcoin.cpp
src/txmempool.cpp
src/txmempool.h
src/validation.h
src/wallet/rpcwallet.cpp
test/bitcoin_functional/functional/test_framework/util.py
test/functional/p2p_feefilter.py
test/functional/test_framework/util.py

Includes an upstream bugfix for feefilter/mempool divergence when the rate is not `%1000=0`.
Does not lower the minimum wallet default! This must be chosen manually for the time being(`settxfee`), at the risk of not propagating to the rest of the network if peers have not also updated. Fee estimation is also not yet updated to support lower feerates.

Reduce relay min rate to 100 sat/vkB

---

test/functional/feature_blocksign.py

The way the test is run, the last node(non-signer) can actually become the block producer.
This, in conjunction with its p2p connection to node 0, means that when node 0 is doing it's compact block back and forth, it can actually create a complete block in 0.5 RTT even if transactions were generated for that block.
Allow this to happen.
This may have been a bug in that the non-signer shouldn't have been making blocks, but this is actually more interesting behavior to test, where sometimes partially-complete compact blocks are made, sometimes full, sometimes empty. This exercises more code paths, and so I'm just making sure this succeeds instead, and assert it only succeeds in the expected situation.

feature_blocksign.py: Allot for possibility of non-empty block 0.5RTT

---

test/functional/feature_fedpeg.py
test/functional/mining_basic.py
test/functional/p2p_segwit.py

Python 3.4 doesn't have .hex(). 3.4 is required by `.python-version` which is used by pyenv. Pyenv users (like myself) will have a hard time running the tests without this.

Use bytes_to_hex_str instead of .hex()

---

src/init.cpp

QT starts up normally, and fails when `-server=1` is set, and continues otherwise, by turning off peg-in validation.
This should be tested on liquidv1 with fresh syncs.

When RPC server disabled, only warn on validatepegin failure

---

src/chainparams.cpp

Currently PAK is blank for anyone running on liquidv1 network. This is wrong.
No PAK list changes are expected prior to dynafed roll-out, so this should remain constant until activation.

Correctly seed the liquidv1 paklist pre-dynafed

---

src/chainparams.cpp
src/dynafed.cpp
src/miner.cpp
src/primitives/block.cpp
src/primitives/block.h
src/test/dynafed_tests.cpp
test/functional/feature_blocksign.py
test/functional/feature_dynafed.py
test/functional/test_framework/messages.py

andytoshi's motivating text:
"Motivation here is that the functionary wants to be able to compute the root of the parameters and use this to look up the params in the set of supported params (which includes a bunch of extra auxiliary data, in particular the signblock witness script).
If the root is computed differently for compact-encoded params than for full-encoded ones, and indeed does not even commit to the extra data, this lookup is impossible without blockchain context, which is not obvious how to obtain for an unsigned block."

HF: Dyanfed pruned header now has extra root

---

contrib/macdeploy/custom_dsstore.py

fixes #724
- generated DS_Store for dmg was referencing Bitcoin-Qt instead
of the locally built application Elements-Qt

macos: Use correct application name

---

src/qt/forms/overviewpage.ui
src/qt/overviewpage.cpp

Makes the balances on the overview page scrollable when therer are lots of assets. It should be both vertically and horizontally scrollable.
Also Fixes the vertical layout so it uses the UI forms and looks better.
Fixes #685

gui: Make balances scrollable on overview

---

src/qt/receiverequestdialog.cpp

fixes https://github.com/ElementsProject/elements/issues/763

Fix QR address display for blinded base58 addrs

---

src/wallet/rpcwallet.cpp

fixes https://github.com/ElementsProject/elements/issues/777
Alternative would be to have the `-chain` name be put there, but honestly seems overkill.

Remove 'bitcoin' from address descriptions

---

contrib/macdeploy/custom_dsstore.py

Backport of https://github.com/ElementsProject/elements/pull/786.

[0.18 backport] macos: Use correct application name

---

src/test/fuzz/script_flags.cpp

Only is compiled with clang/fuzzer setups I suppose.

Fix VerifyScript calls in fuzz/script_flags

---

src/wallet/rpcdump.cpp

resolves https://github.com/ElementsProject/elements/issues/802

getwalletpakinfo: Use offline counter when reporting lookahead

---

src/wallet/rpcdump.cpp

backport of 'getwalletpakinfo: Use offline counter when reporting lookahead'

---

src/bitcoin-cli.cpp
src/chainparamsbase.cpp
src/chainparamsbase.h
src/init.cpp
src/qt/guiutil.cpp
src/test/util_tests.cpp
src/util/system.cpp
src/util/system.h

This fixes f.e. that when arguments are set in CLI or the config file
without a network attached (`port` instead of `liquidv1.port`), they
will now be assigned to the liquidv1 instead of Bitcoin mainnet.
------
With 
```toml
port=9953
```
Before:
```
➜  elements git:(master) ✗ ./src/elementsd -chain=elementsregtest | rg 9953
Warning: Config setting for -port only applied on elementsregtest network when in [elementsregtest] section.
➜  elements git:(master) ✗ ./src/elementsd -chain=main | rg 9953           
➜  elements git:(master) ✗ ./src/elementsd -chain=liquidv1 | rg 9953   
Warning: Config setting for -port only applied on main network when in [liquidv1] section.
```
After:
```
➜  elements git:(master) ✗ ./src/elementsd -chain=elementsregtest | rg 9953
Warning: Config setting for -port …
```

Add DEFAULT chain and set to liquidv1

---

src/wallet/rpcwallet.cpp
test/functional/feature_fedpeg.py

Fixes #812. @stevenroose, take a look when you get back?
Fix multiple issues with claimpegin and createrawpegin support for
multiple loaded wallets:
- Failure to call EnsureWalletIsAvailable would cause a crash when multiple
wallets were loaded, but one was not specified in the RPC call.
- Failure to propagate the request URL from claimpegin when making an
internal call to another RPC would result in failure when multiple
wallets were loaded, by failing to specify one for that call.
Add a regression test to the feature_fedpeg.py test: at a critical point,
create a second wallet on the sidechaind, and set up the RPC client to
use the first one, to check that it still works correctly.

Fix claimpegin and createrawpegin support for multiwallet.

---

src/init.cpp
src/validation.cpp

Now it also shows with `-validatepegin=0`.

Place the mainchain RPC warmup message in a better place

---

src/wallet/wallet.h
test/functional/feature_issuance.py

This follows the reduction of the `minrelaytxfee` in the previous release to the same value. Using this value, the wallet will be able to make transactions with a 0.1 sat/vbyte fee by default.

Reduce mintxfee to 0.1 sat/vbyte and fallback fee to 2 sat/vb

---

src/blind.cpp
src/blind.h
src/init.cpp
src/test/blind_tests.cpp
test/functional/feature_confidential_transactions.py

Replaces https://github.com/ElementsProject/elements/pull/793 and is basically that MR but rebased. (I can't rebase on Greg's branch.)

Switch default bits of hiding to 52

---

src/index/txindex.cpp
src/test/txindex_tests.cpp
test/functional/feature_connect_genesis_outputs.py

This reverts commit ed12d5df1ba52b5ef3dd3799de26bb5e1d3fc654 in which Core removed the genesis txs from the txindex.
Since they are spendable in Elements (as opposed to Core), they should be added to the index as well.

Index the genesis block with txindex

---

src/index/txindex.cpp
src/test/txindex_tests.cpp
test/functional/feature_connect_genesis_outputs.py

Backport of https://github.com/ElementsProject/elements/pull/838.

[0.18 backport] Index the genesis block with txindex

---

src/blind.cpp

As per @dgpv's suggestion here: https://github.com/ElementsProject/elements/pull/834#discussion_r396333202
@dgpv could you review?

Remove the min(max( construction for the ct_exponent argument

---

doc/build-osx.md

on macOS 10.14.6 (Mojave) at least the following tools are required from homebrew:
- libicns provides png2icon
- imagemagick provides convert

Update macOS build instructions to support building dmg

---

src/blind.cpp

Backport of https://github.com/ElementsProject/elements/pull/840.
@dgpv Could you review again?

[0.18 backport] Remove the min(max( construction for the ct_exponent argument

---

README.md

The RPC docs are a great way to understand the difference between Bitcoin and Elements. 
It should be highlighted along with the other differences from Bitcoin Core in the same section.
Alternatively, add them to Elements/Doc

Add link to RPC docs in readme

---

src/blind.h
src/policy/fees.cpp
src/policy/fees.h
src/wallet/wallet.cpp

The fee estimation buckets also have a minimum of 1000 sat/kB.
This PR lowers that limit and also discards old estimates files.

Support fee estimation for fees lower than 1 sat/byte

---

src/blind.cpp
src/blind.h
src/issuance.cpp
src/issuance.h

This is in response to @dgpv 's https://github.com/ElementsProject/elements/issues/842.
I'm not 100% confident this is correct, but it seems so. It also passed all tests on my machine.

[RFC] Remove GetNumIssuance from BlindTransaction assert

---

src/qt/guiconstants.h
src/qt/networkstyle.cpp

This should be the last mention of `#if LIQUID` and `Liquid-Qt` that my grep can find.

Remove another mention of Liquid-Qt

---

src/qt/guiconstants.h
src/qt/networkstyle.cpp

Backport of https://github.com/ElementsProject/elements/pull/855.

[0.18 backport] Remove another mention of Liquid-Qt

---

src/confidential_validation.cpp
src/consensus/tx_verify.cpp

Backport of https://github.com/ElementsProject/elements/pull/863.

[0.18 backport] Fix HasValidFee potential overflow

---

src/confidential_validation.cpp
src/consensus/tx_verify.cpp

Dmitry pointed out this potential overflow. They can't really happen
because of the `CheckTransaction` check on explicit amounts that
happens earlier in the verification chain. But it's a good idea to
add the check here as well so that a potential relaxing of other rules
cannot accidentally introduce an overflow risk.

Fix HasValidFee potential overflow

---

src/rpc/rawtransaction.cpp
test/functional/feature_issuance.py

Fixes https://github.com/ElementsProject/elements/issues/853.

Make issuance fail for invalid addresses 

---

src/rpc/rawtransaction.cpp
test/functional/feature_issuance.py

[0.18 backport]  Make issuance fail for invalid addresses 

---

doc/build-freebsd.md

Fixes #814 by setting basic build configuration:
* Use gmake instead of make
* Use clang instead of gcc
* Add /usr/local to include path

Update build docs for FreeBSD 12.1-RELEASE

---

configure.ac

Backport of my upstream fix https://github.com/bitcoin/bitcoin/pull/19356 .
Net effect is to change the include order slightly for macOS homebrew users with BDB 4.8 installed privately (not linked into system directories) -- our configure scripts will prefer BDB 4.8 if they find it there, even if it is not system default. This fixes a build break that would occur in this situation when some _other_ BDB _is_ installed in system directories. The previous search order would use headers from system directories, but libs from 4.8, causing a crash.
----
On OS X, when searching Homebrew keg-only packages for BDB 4.8, if we find it,
use BDB_CPPFLAGS and BDB_LIBS instead of CFLAGS and LIBS for the result. This
is (1) more correct, and (2) necessary in order to give this location
priority over …

build: Fix search for brew-installed BDB 4 on OS X (backport of upstream fix)

---

src/rpc/rawtransaction.cpp
test/functional/feature_issuance.py

Fixes #885. This is a more comprehensive alternative to #887.
One note: The existing code claimed to assume (and mostly did assume) that fee outputs always go at the end. Other code does not necessarily appear to assume that. I have added explicit checks for it, so it should be obvious enough if it causes problems in practice (and with a small fix, the integration tests do pass.) If we're concerned about whether the assumption is valid, I'm willing to relax the assumption (but then the old code makes even less sense.)
@stevenroose for review? (@jhfrontz also, since #887 was yours so maybe you have opinions.)

Fix logic issues with randomization of outputs in [re]issueasset_base; minor refactoring.

---

contrib/gitian-descriptors/gitian-linux.yml
contrib/gitian-descriptors/gitian-liquid-linux.yml
contrib/gitian-descriptors/gitian-liquid-osx.yml
contrib/gitian-descriptors/gitian-liquid-win.yml
contrib/gitian-descriptors/gitian-osx.yml
contrib/gitian-descriptors/gitian-win.yml

This removes the hardcoded `wget` of libsrvg2-2 package from the internal gitian `script` and instead uses the `packages` capability (the `wget`-based implementation causes unintended dependencies on internet infrastructure; it is also brittle).

Use gitian infrastructure to install librsvg2-2 (in lieu of hard-coded wget)

---

.travis/lint_04_install.sh

Update shellcheck URL per  per https://github.com/koalaman/shellcheck/issues/1871 to unbreak CI.

Update shellcheck URL

---

test/functional/rpc_signrawtransaction.py

- This test assumes a fix for #904. Before correction, the test will result in an error.
- I splited the node network in rpc_signrawtransaction.py to do this test.
- For now, I have only created one test case. Are there any other test cases that should be added?

Add signrawtransactionwithkey test with amount commitments

---

src/blind.cpp
src/blind.h
src/rpc/rawtransaction.cpp
src/rpc/rawtransaction.h
src/wallet/rpcwallet.cpp

When we decode or sign a PSBT given to us via RPC, first check that, if it contains blinded output values, they verifiably match the unblinded output values contained in the original transaction proposal. Otherwise fail.

When decoding or signing a PSBT, check blinded values.

---

src/chainparams.cpp
src/consensus/params.h

Bit: 25 (identical to current elementsregtest dynafed bit)
Start: block 1,000,000 (recent past)
Timeout: never

Specify BIP9 deployment for DynaFed

---

src/bench/verify_script.cpp
src/script/generic.hpp
src/script/interpreter.cpp
src/script/interpreter.h
src/script/sign.cpp
src/script/sign.h
src/test/multisig_tests.cpp
src/test/script_tests.cpp
src/test/sighash_tests.cpp
src/test/txvalidationcache_tests.cpp
src/validation.cpp
test/functional/feature_assumevalid.py
test/functional/feature_block.py
test/functional/feature_blocksign.py
test/functional/feature_sighash_rangeproof.py
test/functional/feature_txwitness.py
test/functional/p2p_segwit.py
test/functional/test_framework/address.py
test/functional/test_framework/key.py
test/functional/test_framework/messages.py
test/functional/test_framework/script.py
test/functional/test_framework/util.py
test/functional/test_runner.py

Add a new sighash flag that includes the rangeproof information in the signature. This avoids certain kinds of malleability in PSBT scenarios.

Add SIGHASH_RANGEPROOF support

---

src/chainparams.cpp
src/rpc/blockchain.cpp
src/validation.cpp
test/functional/feature_dynafed.py

- support blocksigners specifying their own activation to make coordination a bit more flexible
- don't force fedpeg script to change in order to change the block signing script

Some minor dynafed improvements

---

src/confidential_validation.cpp

That is enforced by the `VerifyAmounts` method for regular transactions
and by the `VerifyIssuanceAmounts` method for issuance values.

Make it clear that the CRangeCheck is not called on explicit values

---

src/chainparams.cpp
src/rpc/blockchain.cpp
src/validation.cpp
test/functional/feature_dynafed.py

[elements-0.18] Some minor dynafed improvements

---

src/chainparams.cpp

[elements-0.18] Specify the dynafed epoch length for liquidv1

---

doc/elements-upstream-tracking.md

This goes along with #954 (which is a tool for assisting the review process) and #935 (which was created using approximately this process.)
It's already had some internal review inside Blockstream, and probably should just get merged now, as a description of the process we're currently trying out; then we can have followup PRs once we know how we feel about it / if we want to revise it.
@stevenroose ?

Process for elements upstream tracking / merging

---

src/chainparams.cpp
src/chainparamsbase.cpp
src/chainparamsbase.h

Add the `liquidv1test` chain, which is meant to more closely track the `liquidv1` chain for realistic testing in CI and on test networks (vs `elementsregtest`, a "custom chain" which has diverged a bit more than I'm comfortable with.)
I also fixed a few stray things that looked like minor mistakes to me (uses of the global `gArgs` instead of the parameter `args`, and the `-chain` help text not mentioning `liquidv1` as the default.)

Add liquidv1test chainparams.

---

doc/pset.mediawiki

Adds the document specifying the new PSET format that #900 implements.
Pulled out of #900

Spec for PSET

---

configure.ac

As a workaround for several elements issues on OSX 10.15 and later, this PR adds the `-fno-stack-check` flag to local (non-cross compile) OSX builds.
Background: There seems to be a general issue with OSX (version >= 10.15) builds and clang's default use of `-fstack-check` which seems to be buggy enough to cause issues with multiple projects.
closes #987 #998
Also related to #782

Adds an -fno-stack-check compile time flag to OSX local builds

---

src/test/fuzz/base_encode_decode.cpp
src/test/util_tests.cpp
src/util/system.cpp
test/functional/feature_includeconf.py

Backport of https://github.com/bitcoin/bitcoin/pull/22279 and https://github.com/bitcoin/bitcoin/pull/22002 and https://github.com/bitcoin/bitcoin/pull/22137

fuzz: backport fixes to fuzzer errors

---

doc/tapscript_opcodes.md

This PR adds a doc describing suggested new opcodes for better script programming with elements. The purpose of these opcodes to aid easier writing of complex scripts like covenants in elements.
This introduces 1) Opcodes for Streaming hashes, 2) Transaction introspection opcodes 3) 64 byte athematic opcodes 4) Some utility conversion opcodes 5) Crypto opcodes for low-level operations and tweaking 6) A cleaner way to write For loops and 7) Changes to existing opcodes. 
The doc also describes a brief rationale for choice. Feedback welcome :)

[Doc] New Opcodes for tapscript

---

doc/taproot-sighash.mediawiki

Thanks to @roconnor-blockstream for writing the first draft of this document.

doc: add document describing Taproot sighashes

---

test/functional/feature_taphash_pegins_issuances.py

Should describe the outputs as an array rather than as an object. (The old behavior has long been deprecated but was eliminated entirely in #900.)
Fixes functional tests which were broken in master by simultaneous merge of #1002 and #900.

test: update `createrawtransaction` call in feature_taphash_pegins_issuances.py

---

src/script/interpreter.cpp

Addressing the review by @roconnor-blockstream on #1002 .

Address post merge feedback for Taphash

---

src/blind.cpp
test/functional/rpc_fundrawtransaction.py

There isn't really any reasonable way to recover from this situation but we can at least gracefully fail instead of triggering an assertation failure.
Fixes #979 
Fixes #880

Fix crash when creating large inputs

---

test/functional/rpc_fundrawtransaction.py

This fixes an undetected merge conflict between #1014 and #900.

test: fix surjectionproof overflow functional test for new RPC changes

---

src/script/interpreter.cpp
src/script/interpreter.h

This is an O(N) operation so we want to make sure that we're not recomputing
it every time we hit the INSPECTTXWEIGHT opcode.

script: cache transaction weight per-transaction

---

src/wallet/wallet.cpp
test/functional/feature_issuance.py

This is fixed completely upstream in 22.0, but for now we need to patch around it.
Discovered while cleaning up the assets tutorial.

Fix another instance of bitcoin #20347 nailing us

---

src/validation.cpp

This brings it up to date with the fixed forward port in https://github.com/ElementsProject/elements/pull/996.

Fix dynafed logging to not duplicate messages

---

doc/pset.mediawiki
src/blindpsbt.cpp
src/blindpsbt.h
src/psbt.cpp
src/psbt.h
src/rpc/rawtransaction.cpp
src/util/error.cpp
src/util/error.h
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
test/functional/rpc_psbt.py

In order for blinded coinjoins with 3 or more parties to work, some fields need to be added, amounts cannot be removed, and some bugs need fixing.
First and foremost is to no longer remove amounts after blinding. Due to a miscommunication, I had believed that part of the goal of PSET was to hide semi private information (such as output amounts) from other parties in the transaction. However this causes the combiner to fail because the unique ID is dependent on those amounts and their commitments. If multiple parties had blinded just their own outputs, then the resulting PSETs would not combine because the amounts had be removed and so the unique ID calculated was incorrect. In order for this combining to work, amounts must be kept after blinding and the unique ID calculation must only use …

PSET: Fix blinded coinjoins with 3 or more parties

---

src/test/fuzz/psbt.cpp

The `psbt.tx` Optional is no longer safe to dereference just because decoding succeeded.

fuzz: update psbt fuzztest for PSBT2 changes

---

src/wallet/rpcwallet.cpp
test/functional/wallet_fallbackfee.py

Produce a much less confusing error message in `claimpegin` in the case that estimatesmartfee fails and no fallbackfee is set.

claimpegin: sanity-check fee in case fallbackfee is disabled, throw explicit exception

---

src/chainparams.cpp
src/test/fuzz/FuzzedDataProvider.h
test/functional/test_framework/p2p.py

We don't want connectivity issues between Liquid and custom test networks.

regtest: change network magic away from liquid v1

---

src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
test/functional/feature_issuance.py

forward port of https://github.com/ElementsProject/elements/pull/993.
Closes https://github.com/ElementsProject/elements/issues/985.

Support supplying contract hash to issueasset RPC

---

src/wallet/wallet.cpp

Upstream disabled the default `fallbackfee` option in 0.17, which caused us some user error reports in 0.18. Re-enable the option in 0.21.

re-enable fallbackfee by default

---

src/chainparams.cpp
src/chainparamsbase.cpp
src/consensus/params.h
src/versionbits.cpp
test/functional/feature_elements_taproot_activation.py
test/functional/test_runner.py

Sets Taproot to start signalling around noon (California time) on Nov 1, 2021, assuming 95% of blocks are produced between now and then.
Will activate after one week of 100% signalling. If we can pull this off on the first or second try, we will beat Bitcoin which currently looks like it will activate on Nov 16.
**Edit:** actually, even without Speedy Trial, there is one full period (week) where Taproot will be "locked in" but not "active". So it will activate on Nov 15 at the earliest.

Define Taproot activation parameters for Liquid

---

src/chainparams.cpp

This is basically a Liquid-prod-ish version of regtest. Its default magic should not collide with that for Liquid prod.

chainparams: change magic bytes for liquidv1test

---

src/pegins.cpp

The value it logs, very frequently, is essentially static, coming straight from the chainparams, and should never change during runtime anyway. (With a small exception that doesn't really matter and is probably not the reason for the log.)

Remove redundant log message in IsValidPeginWitness

---

doc/pset.mediawiki

Typos in pset doc

---

src/wallet/rpcwallet.cpp

In `sendtomainchain_pak()` a check is made if the associated `descriptor` is null and an attempt to remedy is made -- but the remedy is never applied to `descriptor` (which results in a SEGV later).  This code fixes that.
Note: unfortunately it also removes the `const` qualifier.  I'm not sure what/if there are conventions for dealing with that (e.g., creating a new `const` of, like, `sanitized_descriptor` for subsequent use in the function?).

Reevaluate descriptor post parse

---

src/net_processing.cpp
src/validation.cpp
src/validation.h

This fixes an issue which causes Elements to download the blockchain headers
multiple times during initial block download.
In particular: each time we receive an INV P2P message with a new block
(about once a minute), we start downloading the headers, again, in parallel
with any existing download(s) in progress.
With this change, after we receive each batch of headers, we check whether
any of the headers in it were new to us. If not (they were all duplicates),
we stop there, and do not ask the peer for another batch. This reduces the
maximum amount of duplication to about 2x, which is not ideal, but a HUGE
improvement.
With luck, this may help with #1013. But it's primarily directed at fixing slow initial block download, which I can't immediately find an open issue for on this repo, but …

Fix elements multiple-header-download issue.

---

src/net_processing.cpp

Fixes: https://github.com/ElementsProject/elements/issues/1084

Remove block from in-flight list when a duplicate is received

---

src/net.h
test/bitcoin_functional/functional/p2p_invalid_messages.py
test/functional/p2p_invalid_messages.py

[BACKPORT 0.18] Raise max P2P message size to account for larger elements dynafed header size

---

src/chainparamsbase.cpp
src/validation.cpp

(cherry picked from commit a06aac152a0b3535890c6a1f0118b255838ae6c5)
Back in 0.18.1.12, dynafed signaling was disabled to simplify some deployments. This was reverted in the 0.21 branch, for consistency, let's revert it here too.

[BACKPORT 0.18] Make dynafed signaling opt-out instead of opt-in

---

src/core_io.h
src/core_write.cpp
src/rpc/blockchain.cpp

Fixes https://github.com/ElementsProject/elements/issues/1102.
Note: the following examples were all run on the liquidv1 network.
Before this change, headers for all dynafed blocks were displayed as follows (note the empty `signblock_witness_*` fields):
```
$ elements-cli getblockheader 68b99e3c1d75663b1d8822c57e5605fedd94d9190db7b01d3d24910576f8ec22
{
"hash": "68b99e3c1d75663b1d8822c57e5605fedd94d9190db7b01d3d24910576f8ec22",
"confirmations": 1,
"height": 1800219,
"version": 536870912,
"versionHex": "20000000",
"merkleroot": "c063fb1a72aa6466e10ffbdb1125809b8d4b3bb87a2a38c8492febac20b8d4a3",
"time": 1650567188,
"mediantime": 1650566888,
"signblock_witness_asm": "",
"signblock_witness_hex": "",
"dynamic_parameters": {
"current": {
"signblockscript": …
```

RPC: correctly display signblock_witness post-dynafed

---

src/rpc/blockchain.cpp
test/functional/feature_blocksign.py
test/functional/feature_dynafed.py
test/functional/rpc_blockchain.py

Fixes https://github.com/ElementsProject/elements/issues/1109.
To summarize, there are currently two similar sets of fields in the `getblockchaininfo` RPC response which purport to describe the network's current blocksigning script:
```
$ elements-cli getblockchaininfo
{
"chain": "liquidv1",
"blocks": 1808648,
...
"signblock_asm": "11 026a2a106ec32c8a1e8052e5d02a7b0a150423dbd9b116fc48d46630ff6e6a05b9 02791646a8b49c2740352b4495c118d876347bf47d0551c01c4332fdc2df526f1a 02888bda53a424466b0451627df22090143bbf7c060e9eacb1e38426f6b07f2ae1 02aee8967150dee220f613de3b239320355a498808084a93eaf39a34dcd6202485 02d46e9259d0a0bb2bcbc461a3e68f34adca27b8d08fbe985853992b4b104e2741 02e9944e35e5750ab621e098145b8e6cf373c273b7c04747d1aa020be0af40ccd6 02f9a9d4b10a6d6c56d8c955c547330c589bb45e774551d46d415e51cd9ad …
```

getblockchaininfo: remove incorrect signblock fields

---

doc/pset.mediawiki

Following discussion with achow101

PSET spec updates

---

contrib/gitian-descriptors/assign_DISTNAME
contrib/guix/libexec/prelude.bash
contrib/shell/git-utils.bash

guix builds are still named `bitcoin-` instead of `elements-`, which is fixed by this PR.
Also, since 21 we've had a problem that our tagged builds are named `elements-elements.....` due to the way we tag, this PR also fixes that for both guix and gitian

Fix tarball names in guix and gitian builds

---

src/qt/networkstyle.cpp

In 0.21.x, custom chains appeared in the title in QT, now it just says regtest. This PR recovers that functionality

QT: fix title in custom chains

---

src/wallet/wallet.cpp

Fixes #1105 
This causes crash on elements wallet when dealing with transactions that
have explicit values and confidential assets. This creates a somewhat
serious DoS attack as the sender can cause the reciever's wallet to
crash by partially blinding the change output. To make matters worse,
the wallet initially accepts the transaction, but fails while spending
the output.
This is likely caused by a combination of two bugs:
1) The wallet's current behaviour stores the complete transaction of interest
in CWalletTx instead of just Outpoints. Only that the spend time do we
iterate over all outputs, try to unblind them and check which are
isMine. When calling wtx.GetOutputValueOut() or similar calls, we hit this assertion.
While the current behaviour is okay, I think the correct way is move …

Check the value assertion only on valid amounts

---

src/wallet/wallet.cpp

(Backport of #1134)
This causes crash on elements wallet when dealing with transactions that
have explicit values and confidential assets. This creates a somewhat
serious DoS attack as the sender can cause the reciever's wallet to
crash by partially blinding the change output. To make matters worse,
the wallet initially accepts the transaction, but fails while spending
the output.
This is likely caused by a combination of two bugs:
1) The wallet's current behaviour stores the complete transaction of interest
in CWalletTx instead of just Outpoints. Only that the spend time do we
iterate over all outputs, try to unblind them and check which are
isMine. When calling wtx.GetOutputValueOut() or similar calls, we hit this assertion.
While the current behaviour is okay, I think the correct way …

[elements-22.x] Backport #1134: Check the value assertion only on valid amounts

---

src/wallet/rpcdump.cpp
test/functional/feature_confidential_transactions.py

This facilitates the following workflow:
1) Obtain an updated psbt with in_witness_utxo and in_utxo_rangeproof
2) Get the blinding key from the input utxo address obtained from input
script pubkey without revealing master blinding key
3) Rewind the proof to obtain blinding factors and implement stateless
blinding

Allow dumpblinding key to accept non-CT address

---

contrib/macdeploy/macdeployqtplus

Mac installer is showing the elements icon in a bad position 
This small fix puts it back where it should be

Fix Icon position in dmg

---

src/blindpsbt.cpp
src/psbt.cpp
src/wallet/wallet.cpp

A few minor cases fixed in PSET-related code. Caused either a crash or invalid transactions created in some cases.

Fixing issuance cases and half blinded cases in PSET

---

src/qt/bitcoinamountfield.cpp

Fixes: #1144
The problem was that Elements uses different defaults for the "step" between coins and assets, but these defaults were ignored after calculation.
This PR just uses the right variable for the step calculation.

Elements-qt: Fix arrows to increase/decrease Amount

---

doc/elements-tx-format.md

**Note**: When reviewing this markdown file, please open it in a markdown viewer. Otherwise, the tables will be illegible. Github will show you the rendered markdown if you open the "Files changed" tab, click the three dots on the top right of the file, and select "View file".
This PR adds a new markdown document which contains a detailed description of the elements transaction serialization format.
The document includes a detailed descriptions of all fields and examples where complex raw transactions are deserialized, step-by-step.
Intended audience:
- Hardware Wallet developers implementing liquid apps
- Developers creating Liquid integrations
- Developers writing their own serialized Liquid transactions from other languages
- Bitcoin users wanting to see what's new in an Elements …

docs: describe elements transaction serialization format

---

doc/pset.mediawiki
src/blindpsbt.cpp
src/blindpsbt.h
src/psbt.h
src/rpc/rawtransaction.cpp

Adds fields for explicit input value and assets, and their proofs. Also adds a flag to indicate whether an issuance should be blinded.
Closes #1153

pset: Add input explicit value, assets, and proofs, and issuance blinding flag

---

share/setup.nsi.in

Fixes https://github.com/ElementsProject/elements/issues/868.
I can't test by lack of Windows machine. @philippem how hard is it for you to run the Gitian build Windows only and test this? I replaced all the capital-B Bitcoin mentions in the file.

[need-test] Fix Bitcoin name usage in Windows installer

---

.cirrus.yml

Currently fuzzer test fails due to the 120 minute timeout, add some CPUs to avoid that

Add more CPUs to the fuzzer test

---

doc/elements-tx-format.md
src/miner.cpp
src/miner.h
src/rpc/client.cpp
src/rpc/mining.cpp
test/functional/rpc_getnewblockhex.py
test/functional/test_runner.py

Modifies the `getnewblockhex` json rpc call to accept an "array" of commitments instead of a single commitment. The given string parameter will be split on spaces. 
Adds a new functional test for this rpc call.
edit: no longer a breaking change

rpc: change getnewblockhex to take multiple commitments

---

src/miner.cpp
src/miner.h
src/rpc/client.cpp
src/rpc/mining.cpp
test/functional/rpc_getnewblockhex.py
test/functional/test_runner.py

Modifies the getnewblockhex json rpc call to accept an array of commitments instead of a single commitment.
Backwards compatibility is maintained by first attempting to parse as a string for a singular commitment.
Related PR: #1155

backport to 0.21: change getnewblockhex to take multiple commitments

---

src/key_io.cpp
test/functional/wallet_address_types.py

Preserve blinding key when parsing taproot address.

---

share/setup.nsi.in

Fixes: https://github.com/ElementsProject/elements/issues/1174
The "before" can be seen in issue https://github.com/ElementsProject/elements/issues/1174

Fix Windows uninstaller icon in "Add or remove programs"

---

src/blindpsbt.cpp
src/rpc/rawtransaction.cpp

Also make sure value rangeproof generation fails if its asset commitment isn't provided.

rpc: decodepsbt: fix check for blind_reissuance_amount_proof output

---

contrib/assets_tutorial/pset_swap_tutorial.py

Fixes the line where the address is obtained from the relevant output.

fix pset swap example

---

src/blindpsbt.cpp
src/blindpsbt.h
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
test/functional/rpc_psbt.py

Add include_explicit to walletcreatefundedpsbt

---

src/rpc/mining.cpp

Instead of RPC_VERIFY_ERROR when the block is already in the chain.
Fixes https://github.com/ElementsProject/elements/issues/927.

Have testproposedblock return RPC_VERIFY_ALREADY_IN_CHAIN

---

src/block_proof.cpp
src/chain.h
src/dynafed.cpp
src/init.cpp
src/miner.cpp
src/net_processing.cpp
src/node/blockstorage.cpp
src/node/blockstorage.h
src/pegins.cpp
src/rest.cpp
src/rpc/blockchain.cpp
src/txdb.cpp
src/txdb.h
src/validation.cpp
src/validation.h
test/lint/lint-locale-dependence.sh

Adds a `-trim_headers` flag, which punts some of the largest header fields out of `CBlockIndex`, the struct used for keeping the in-memory copies of the headers of the whole chain. We keep several dynafed periods worth of headers fully in memory, so that we can be assured of being able to validate new blocks; additionally, during IBD we keep a window of headers in-memory past where we have blocks validated (but restrict the size of the window, so that memory usage does not balloon too much.)
If the chain is not configured for dynafed, the default value for the dynafed period is very large, so my guess is this code will do basically nothing in that case (it will have a window of headers to keep which is larger than the entire chain), but I haven't tested that.
Turning the flag on while in …

Improve elements memory usage

---

src/rpc/blockchain.cpp

- described order of current_fedpegscripts array was incorrect

Correct help for getsidechaininfo RPC

---

src/chainparams.cpp
src/chainparamsbase.cpp
src/consensus/params.h
src/dynafed.cpp

Fixes: https://github.com/ElementsProject/elements/issues/1208

Allow deploying regtest networks with p2wsh peg-ins

---

contrib/review-prs.py

Improve the merge PR review script (for handling merges between upstream bitcoin core and elements) in a bunch of ways, including:
- More types of diffs to optionally look at
- Better handling of non-merge fixup commits
- Handling of new types of Bitcoin Core merge commits

Improvements to pr review script

---

src/net_processing.cpp
src/node/blockstorage.cpp
src/node/blockstorage.h

Fixes: https://github.com/ElementsProject/elements/issues/1211

Fix underflow when blocks are ahead of headers

---

contrib/review-prs.py

Fix linter by removing some trailing whitespaces introduced by https://github.com/ElementsProject/elements/pull/1118

Fix linter (trailing whitespace)

---

src/rpc/mining.cpp

The help message for `testproposedblock` erroneously indicates that some checking will be done against the PAK list.  There are no [longer any] such checks.

Correct testproposedblock help

---

src/qt/sendcoinsdialog.cpp

Fixes: https://github.com/ElementsProject/elements/issues/1221
Leaving it as draft since it's based on https://github.com/ElementsProject/elements/pull/1222 (which hasn't been merged yet).

Elements-qt: Use available balance from the currently selected asset

---

src/chain.h
src/rpc/blockchain.cpp
src/txdb.cpp

This MR fixes 2 crashes:
1) assert in blockheaderToJSON when checking for dynafed block on a trimmed header
2) crash in blocktoJSON/blockheaderToJSON due to loaded block being incomplete.
Fixes: https://github.com/ElementsProject/elements/issues/1224

RPC: Avoid assert by keeping a flag to identify trimmed dynafed blocks

---

src/validation.cpp

I cannot test this because of #1238 and #1237 as well as the lack of functionality in the PSBT RPCs, inability to inform the wallet about a UTXO without broadcasting the transaction it comes from, etc etc.

testmempoolaccept: feed genesis hash into sighash computation

---

ci/test/04_install.sh
src/test/script_tests.cpp
test/functional/feature_taproot.py

Fixes the `script_assets_test` by changing the `feature_taproot.py` functional test to include the genesis block hash when dumping the json tests. The asset tests were failing with the Taproot flag enabled, because the Elements Taphash calculation requires the genesis block hash. 
Requires the json file from https://github.com/ElementsProject/qa-assets/pull/1
Steps to run the test: 
- compile this branch with tests enabled 
- checkout my updated branch of the qa-assets repo in the PR above 
-  run the test `DIR_UNIT_TEST_DATA=/path/to/qa-assets/unit_test_data ./src/test/test_bitcoin -t script_tests/script_assets_test`

test: re-enable and fix script assets test 

---

src/wallet/rpcwallet.cpp
test/functional/feature_confidential_transactions.py
test/functional/feature_sighash_rangeproof.py
test/functional/rpc_signrawtransaction.py

fixes #1245 - `getnewaddress` will now return an unblinded bech32 address even when `-blindedaddresses=1` in config

fix: getnewaddress - don't blind bech32 addresses

---

doc/elements-confidential-transactions.md

Linter is complaining about whitespaces in `doc/elements-confidential-transactions.md`, fix them

Whitespace fixes to calm down the linter

---

src/net_processing.cpp
test/lint/lint-python-utf8-encoding.sh
test/lint/lint-spelling.ignore-words.txt

These commits fixes a few linting issues for codespell, and excludes `src/secp256k1/` from the python utf8 linter. 
The linters run cleanly on the master branch with these commits applied. However, on the `elements-22.x` branch there are 2 other lints in `doc/release-notes.md` that can be fixed by this diff: 
```diff
diff --git a/doc/release-notes.md b/doc/release-notes.md
index 972c91aa6f..f94437a884 100644
--- a/doc/release-notes.md
+++ b/doc/release-notes.md
@@ -744,7 +744,7 @@ A detailed list of changes in this version follows. To keep the list to a manage
- bitcoin/bitcoin#21185 fuzz: Remove expensive and redundant muhash from crypto fuzz target (MarcoFalke)
- bitcoin/bitcoin#21200 Speed up `rpc_blockchain.py` by removing miniwallet.generate() (MarcoFalke)
- bitcoin/bitcoin#21211 …
```

lint: fix codespell and python utf8 encoding lint issues (redux)

---

src/chain.h
src/init.cpp
src/rpc/blockchain.cpp

Preparing for the new version of trim headers, both in 22 and 23, there are a few commits that don't create conflicts and that it would be easier to have before branching.

Small fixes in preparation for trim_headers version 2

---

doc/elements-block-header-format.md

adds a doc that describes the serialization of block header fields, and a few examples of deserializing block headers from hex  
[rendered](https://github.com/ElementsProject/elements/blob/dd606cecf7aa76df743218fb538624fedf16474b/doc/elements-block-header-format.md)

docs: add block header serialization doc and examples

---

test/functional/rpc_signrawtransaction.py

This PR fixes occasional flaky test behaviour  in `signrawtransaction.py`, by increasing the Decimal precision in the CLTV test.
When the selected UTXO in the test has many decimal places, then using precision 8 for the `amt` calculation results in an incorrect value. 
```python
Python 3.10.12 
>>> from decimal import *
>>> getcontext().prec = 8
>>> 1 + Decimal(50.00005640) - Decimal(0.00001)
Decimal('51.000046')
>>> getcontext().prec = 10
>>> 1 + Decimal(50.00005640) - Decimal(0.00001)
Decimal('51.00004640')
```
fixes #1269 at least partially, I ran this test in a loop for 15 minutes without failure

test: fix flaky CLTV test in signrawtransaction.py

---

src/rpc/rawtransaction.cpp
src/wallet/coinselection.cpp
src/wallet/spend.cpp
test/functional/test_runner.py
test/functional/wallet_elements_regression_1259.py

- KnapsackSolver applies non_policy_effective_value incorrectly to policy output amount. This leads to a negative expected fee in lots of inputs with few outputs scenarios (e.g. utxo consolidations). Fixed that and added a comment.
- Without this fix, an assert on policy change amount vs fee paid will trigger (spend.cpp:1449). I consider asserts too aggressive a check for these kinds of condition (this will crash elements unless an explicit handler for SIGSEVs is registered). I took to liberty of replacing the assert with a log event and graceful failure (returning false).
- No new tests was added to cover for this issue,  functional tests pass.

KnapsackSolver fix

---

src/rpc/rawtransaction.cpp
src/wallet/coinselection.cpp
src/wallet/receive.cpp
src/wallet/spend.cpp
src/wallet/test/wallet_tests.cpp
test/functional/example_elements_code_tutorial.py
test/functional/test_runner.py
test/functional/wallet_elements_regression_1259.py

same diff as #1258 but for `master` branch

fix: assert failure on non-policy asset consolidation in CreateTransactionInternal 

---

src/pubkey.cpp
src/test/script_tests.cpp
test/functional/feature_taphash_pegins_issuances.py
test/functional/feature_tapscript_opcodes.py
test/functional/test_runner.py
test/functional/wallet_groups.py

Fixes issue which was causing validation to fail on block 2a70e30a3b975b53a0598139f6f490ff0865a47d0028a55ddc04451270d228d0 in liquidtestnet.
This bug was introduced in the merge of https://github.com/bitcoin/bitcoin/pull/22448 in https://github.com/ElementsProject/elements/commit/09333e2aca97bc819aed26eb2835df7cf604c38d.
It is not yet clear why only a testnet block is affected by this issue, and why the production liquid chain syncs fully.
Subsequent commits in this PR contain fixes for various failing functional tests.

pubkey: fix VerifySchnorr bug which is causing testnet validation failure

---

src/wallet/rpc/elements.cpp

Fixes: https://github.com/ElementsProject/elements/issues/1282

Remove constrains on liquidv1 pegout bitcoin descriptor

---

src/wallet/rpc/elements.cpp

To avoid cases like https://github.com/ElementsProject/elements/issues/1318

getpeginaddress cannot be trusted during ibd, it should fail

---

test/functional/rpc_tweakfedpeg.py
test/functional/wallet_elements_regression_1263.py

Fixes 2 functional tests failing since PR #1327 which changed getpeginaddress to only be valid when IsInitialBlockDownload is false

test: fix tests broken by change to getpeginaddress

---

Makefile.am
configure.ac

- enables coverage for the simplicity build when elements is built with `--enable-lcov` 
- filters `src/simplicity/secp256k1` from results (since `src/secp256k1` is also filtered by upstream)  
example output: 
qa-assets from https://github.com/uncomputable/asset-gen thanks @uncomputable 
configured with: `./configure --enable-lcov --with-incompatible-bdb --with-seccomp=no` 
built with: `DIR_UNIT_TEST_DATA=/path/to/qa-assets/unit_test_data make -j15 cov` 
uploaded results here: https://simplicity-coverage.netlify.app/

simplicity: enable coverage in configure.ac

---

src/qt/rpcconsole.cpp

Issuing assets via the elements-qt console interface on MacOS arm platforms causes the process to crash.  This appears to be because the secondary threads on MacOS default to a 512k stack (per https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Multithreading/CreatingThreads/CreatingThreads.html via https://stackoverflow.com/a/23609290 ) -- this in comparison to linux threads that apparently have 8M of stack.
This change forces the QT-related threads to have an 8M stack.

Ensure that arm-macos environments have sufficient QT thread stack

---

src/chainparams.cpp
src/init.cpp
test/functional/feature_discount_ct.py

The default for acceptdiscountct in liquidv1 was changed to false in #1317 without the corresponding doc being updated. 
Also fixes that creatediscountct should override the acceptdiscountct setting.

discount: fix init doc for acceptdiscountct and override for creatediscountct

---

src/wallet/rpc/elements.cpp

Fixes the size estimation for pegin transactions, the witness scale factor was only being applied to the pubkey and not the rest of the witness data. 
The overestimation is ~56 bytes 
```
>>> (1+1+72+1+33/4)
83.25
>>> (1+1+72+1+33)/4
27.0
>>> 83.25 - 27.0
56.25
```

fix: size estimation for pegin transactions

---

src/chainparams.cpp

Fixes: https://github.com/ElementsProject/elements/issues/1359

Accept discount-ct by default in liquidtestnet

---

src/core_write.cpp
src/policy/discount.h
test/functional/feature_discount_ct.py
test/functional/feature_discount_ct_ordering.py

fixes the discount calculation by multiplying the amount and nonce discounts by the witness scaling factor (4) as they form part of the base transaction. thanks to @jgriffiths !
also adds `discountweight` next to `discountvsize` in TxToUniv response if node accepts Discount CT

discount: fix weight calculation

---

src/qt/bitcoinunits.cpp

Fixes: https://github.com/ElementsProject/elements/issues/1373

Use LBTC instead of L-BTC in QT

---

src/wallet/wallet.cpp

Related to https://github.com/bitcoin/bitcoin/issues/31474 upstream.
Fixes a crash in QT when loading an old wallet with many coinbase txs

Wallet: avoid scanning after the last known block

---

src/asset.h
src/blind.cpp
src/rpc/rawtransaction.cpp
src/rpc/util.cpp
src/rpc/util.h
src/wallet/receive.cpp
src/wallet/rpc/elements.cpp
src/wallet/rpc/spend.cpp
src/wallet/spend.cpp
src/wallet/wallet.cpp
test/functional/test_runner.py
test/functional/wallet_elements_21million.py

allows issuing/reissuing/sending/receiving of more than 21 million of non-policy assets 
adds a functional test

assets: allow issuance and transaction amounts of more than MAX_MONEY for non-policy assets

---

src/primitives/confidential.h
src/primitives/transaction.h
src/test/fuzz/rbf.cpp

I ran all the non-Simplicity fuzztests for 100 CPU-hours and found 3 crashes. Two are minor things which are fixed here. Another was in deserializing PSBTs, which needs more investigation, so I did not address.

A couple miscellaneous fixes for fuzztests

---

test/functional/example_elements_code_tutorial.py
test/functional/feature_discount_ct.py
test/functional/feature_discount_ct_ordering.py
test/functional/feature_taphash_pegins_issuances.py
test/functional/feature_tapscript_opcodes.py
test/functional/feature_trim_headers.py
test/functional/wallet_elements_21million.py
test/functional/wallet_elements_regression_1263.py

Several tests are failing in the mac native builds because they only have descriptor wallets, peg-ins/peg-outs/initialfreecoins are not available yet for descriptor wallets so we need to disable them.
Also the 21M test fails in descriptor wallets but for different reasons, the wallets have different names

Fix some functional tests when bdb is not available

---

.cirrus.yml
build_msvc/libbitcoin_wallet/libbitcoin_wallet.vcxproj.in
build_msvc/libbitcoinconsensus/libbitcoinconsensus.vcxproj
build_msvc/test_bitcoin/test_bitcoin.vcxproj
ci/test/00_setup_env_i686_centos.sh
ci/test/00_setup_env_native_tsan.sh
ci/test/04_install.sh
ci/test/05_before_script.sh
depends/packages/boost.mk
depends/packages/xcb_proto.mk
src/mapport.cpp

This MR fixes 3 things, but there are some still missing.
Fixed:
1.  Win64 native build
2. CentOS 8 test (moved to Rocky Linux 8)
3. TSAN test (moved to clang-18 in an updated image, test is still flaky due to parallelism, works well with `-j1`)
Still missing:
1. macOS native build, will fix after the move to arm64
2. Stabilize TSAN, either find the issue or move to `-j1`)
3. Windows native tests are still failing

CI: Fix Win64 native build, TSAN and CentOS 8 test

---

src/chain.h
src/node/miner.h
src/rpc/mining.cpp
src/test/fuzz/witness_program.cpp
src/txmempool.cpp
src/txmempool.h
test/sanitizer_suppressions/ubsan

Mostly straightforward stuff in here, except that we needed to backport https://github.com/bitcoin/bitcoin/pull/23418, which in turn required https://github.com/bitcoin/bitcoin/pull/24625.
This does not fix the PSET RPC-related crash but it does fix various ubsan lints (and a couple actual crashes) for other parts of the codebase.

various bugfixes for new fuzz test vectors

---

src/txmempool.cpp
src/txmempool.h
test/sanitizer_suppressions/ubsan

Some combination of rebasing and the fact that MarcoFalke is clearly grinding his commit hashes to all start with `fa` led to these being dropped in #1399.

more fuzzer fixes (continuation of #1399)

---

src/Makefile.test.include
src/test/fuzz/simplicity.cpp
src/test/fuzz/simplicity_compute_amr.c
src/test/fuzz/simplicity_tx.cpp
test/sanitizer_suppressions/ubsan

This PR adds a new fuzz target. I will post a separate PR to the qa-assets repo to add an initial seed corpus later today, once I am done combining and minimizing the results from my various local runs.
This fuzz target takes its seeds in a simple and well-defined format: a four-byte LE budget, then a transaction, Simplicity program and witness, each prefixed by a four-byte LE length. The fuzz target extracts any additional randomness it needs from the txid of the first input of the transaction, since this data is not interpreted in any other way we therefore won't confuse the fuzzer.
The reason for this design, rather than a more typical "just query the fuzzer when you need stuff", is to make it possible to fairly easily generate test vectors from sources other than this fuzz test. (For …

simplicity: add fuzz target

---

.cirrus.yml
build_msvc/bench_bitcoin/bench_bitcoin.vcxproj.in
build_msvc/bitcoin-cli/bitcoin-cli.vcxproj
build_msvc/bitcoin-qt/bitcoin-qt.vcxproj
build_msvc/bitcoin-tx/bitcoin-tx.vcxproj
build_msvc/bitcoin-util/bitcoin-util.vcxproj
build_msvc/bitcoin-wallet/bitcoin-wallet.vcxproj
build_msvc/bitcoind/bitcoind.vcxproj
build_msvc/test_bitcoin-qt/test_bitcoin-qt.vcxproj
build_msvc/test_bitcoin/test_bitcoin.vcxproj

Continuing with the Win64 native build fixes, we realized that the resulting binaries still had the bitcoin name. This MR fixes the TargetName for the executables, which makes the unit tests pass correctly and some of the functional tests pass too. Given that it's not a high priority for functional tests to pass with the native builds, added the `|| true` to make sure it "passes" but we can still monitor what it's doing.
We'll keep monitoring and fixing the failures, but in background.
Nit: these patches do fix 23.3.x and 23.2.x, but are not enough for fixing everything in master (yet)

Fix native win64 build (part 2)

---

contrib/merge-prs.sh

We've been using this for quite awhile but as far as I know it was not at any point checked in.
This PR also contains minor changes of mine, but the bulk of the code is written by Andrew Poelstra. (I have attributed the main commit to him, although I'm not 100% sure it doesn't contain any changes from me.)

Check in Andrew's script for merging changes into Elements integration branch

---

contrib/merge-prs.sh
test/lint/lint-spelling.ignore-words.txt
test/lint/lint-spelling.sh

Should fix lint ci job that I broke when merging #1210

lint: fix shellcheck, spelling, and locale

---

src/simplicity/eval.c

Simplicity

---

src/test/fuzz/simplicity_tx.cpp

There was a bit of dead code laying around, and also we weren't hitting the `ERR_CMR` error return of the Simplicity interpreter. The former is easy and the latter I was able to hit with a little bit of trickery, without duplicating any work or requiring any new test seeds.

fuzz: minor updates to the Simplicity fuzz tests

---

src/psbt.h

I mentioned in one of my fuzz seed PRs that I couldn't provide seeds for the `psbt_input_deserialize` target because they were crashing.
This PR fixes the crash. I will PR to the fuzz seeds repo shortly.

pset: fix NULL pointer dereference when deserializing malformed PSETs over RPC

---

build_msvc/bitcoind/bitcoind.vcxproj
src/block_proof.cpp
src/net_processing.cpp
src/rpc/request.cpp
test/functional/feature_confidential_transactions.py
test/functional/feature_discount_ct.py
test/functional/feature_fedpeg.py

In feature_discounct, the created tx can be of 2 different weights, we need to make sure we don't fail erroneously.
Newer gcc versions complain about mixing int and enum, so we need to do the 0 from the enum.
TSAN revealed an unlocked access to pindexBestHeader, so it's moved inside the lock
Fixes an issue in windows builds accessing the cookie file with special characters in the path.
Also addresses some issues seen in Win 64 native functional tests, doesn't fully fix the issues, but it's a step in the right direction.
Fixes: https://github.com/ElementsProject/elements/issues/1406 https://github.com/ElementsProject/elements/issues/1422

Fix tests and build warnings

---

src/primitives/confidential.h
src/wallet/spend.cpp

Not sure why this is not affecting linux builds too, but when `fillBlindDetails` adds the `OP_RETURN`, `change_position` still points to the old tx, we should update it to the new one.
Fixes 4 previously failing tests in win64.
```
feature_confidential_transactions.py --legacy-wallet
feature_issuance.py --legacy-wallet
wallet_basic.py --legacy-wallet
wallet_watchonly.py --legacy-wallet
```

Fix Assert crash in win64 native builds

---

test/functional/test_runner.py
test/functional/wallet_elements_dust_relay.py

re #1433
adds a functional test showing dust threshold values for blinded outputs using Elements RPCs

test: add dust relay output value test

---

src/chainparams.cpp
test/functional/feature_elements_simplicity_activation.py

When DynaFed is active, trying to activate Simplicity with version bit 24 causes [`ContextualCheckDynaFedHeader`](https://github.com/ElementsProject/elements/blob/b63f7ab9b5e710fcd4e87f92c1981ea5f9c71bd1/src/validation.cpp#L3709) to fail with `CreateNewBlock: TestBlockValidity failed: invalid-dyna-fed, dynamic block header has unknown HF extension bits set`.

fix: simplicity activation when dynafed is active

---

src/blindpsbt.cpp
src/confidential_validation.cpp
test/functional/feature_confidential_transactions.py

Add checks that surjection proof and range proof are present when tx is confidential, and if not return error. 
Additional functional tests to verify correct behaviour.

Add missing proof checks and tests

---

src/chainparams.cpp

We operate a cluster of about ~50 liquid and liquid testnet nodes globally for the liquid.network explorer. The liquid.network hostname is a round-robin DNS for our BGP anycast cluster of nodes from Ashburn, Frankfurt, Tokyo, Singapore, and Honolulu. You can see the full list at https://liquid.network/monitoring
Since we now accept incoming connections for Liquid P2P on 7042/tcp and for Liquid Testnet P2P on 18891/tcp, this PR adds liquid.network as a DNS seed for both networks, which should hopefully improve the P2P connectivity.

Add liquid.network DNS seed

---

src/chainparams.cpp

Remove dummySeed.invalid. from liquidtesnet

Avoid adding invalid seeds to liquidtestnet

---

src/chainparams.cpp

This patch simply starts signalling for Simplicity in any blocksigner that has it enabled. Once we have one week (10080 blocks) of unanimous signalling, then it activates.

simplicity: activate on first week of unanimous signalling after block 3333333

---

src/util/syscall_sandbox.cpp

Unlike in Bitcoin, our message handling thread needs to open sockets in order to call out to the mainchain RPC interface. We recently brought in a seccomp syscall whitelist from upstream, which is enabled on my local CI box (though apparently not on Github CI) and it is failing on this.

syscall: whitelist network access for msghand thread

---

src/addrman.cpp
src/addrman_impl.h
src/test/fuzz/addrman.cpp

https://github.com/bitcoin/bitcoin/pull/30568
https://bitcoincore.org/en/2025/03/31/disclose-cve-2024-52919/

Cherry-pick bitcoin#30568: addrman: change internal id counting to int64_t

---

test/functional/mempool_unbroadcast.py

The `mempool_unbrodcast.py` test was generating a list of 57 confirmed UTXOs and then performing a spend from the same wallet, using a random UTXO. The unmodified list was then used to create a raw transaction, causing a mempool conflict and test failure with a chance of 1/57. 
This fix updates the UTXO list with the spend. 
Fixes https://github.com/ElementsProject/elements/issues/1457

Fix `mempool_unbroadcast.py` test

---

src/rpc/rawtransaction_util.cpp
test/functional/feature_issuance.py
test/functional/rpc_rawtransaction.py

`ConstructTransaction` now checks for duplicate input address/asset pairs instead of just duplicate addresses. The enables the creation of transactions that send multiple assets to the same address. 
https://github.com/ElementsProject/elements/issues/1429

Enable sending of different assets to the same address

---

src/policy/policy.h
src/validation.cpp

Taproot and other soft-forks historically in Bitcoin have not gated mempool access.

Unconditionally accept Simplicity spends in the mempool

---

src/chainparams.cpp

`accept_unlimited_issuances` for `CLiquidV1TestParams` configurable and uses default from `CLiquidV1Params`.

acceptunlimitedissuances configurable for CLiquidV1TestParams
