alpha-README.md
Improves readability on Github and other Markdown viewers
=> Fix markdown to improve readability of alpha-README.md

contrib/sidechain-manipulation.py
=> Limit send-to-sidechain transaction size

src/wallet.cpp
Whenever some inputs are blinded, but no outputs are, forcibly add a 0-value OP_RETURN output.
Also fix a bug to not complain when a blinded change output was already added in this case.
=> Support creating blinded inputs without blinded output

src/addrman.cpp
This reduces idle CPU usage for me from 40% to 1%.
=> Improve addrman Select() performance when buckets are nearly empty.

src/coins.cpp
=> Fix overflow in priority calculation

src/chainparams.cpp, src/chainparams.h
=> Chainparams: fix the factory the #6907 way

contrib/fedpeg/withdrawwatch.py
This, in addition to https://github.com/jgarzik/python-bitcoinrpc/pull/56, should fix many ww errors.
=> Add some additional error handling in ww for slow bitcoinds

README.md
The Elements repository is to be the starting point for many developers hoping to work on sidechain technology.  This proposal adds easily navigable links and messaging that guides those developers to further study.
=> Improve README, Add Documentation

fedpeg-README.md
The changes from this fetch-merge were merged in [#86](https://github.com/ElementsProject/elements/pull/86).
=> remove now-unnecessary fetch-merge that was merged in PR#86

src/init.cpp
=> Trivial: s/liquid-daemon/elementsd

src/bitcoin-cli.cpp
Some missing string replacements.
=> Fix elements-cli help: s/bitcoin-cli/elements-cli/

src/init.cpp, src/main.cpp, src/script/interpreter.cpp, src/script/script.h
=> Document -signblockscript and -fedpegscript in daemon help

src/script/ismine.cpp
=> Handle TX_FEE case in IsMine

src/main.cpp
No issues seen in the wild, and it's unlikely, but a block to be reconsidered may not get added if another is being deleted.
=> rpc watchdog should take cs_main to protect the reconsiderblock queue

qa/rpc-tests/wallet.py, src/rpc/blockchain.cpp, src/rpc/rawtransaction.cpp, src/wallet/rpcwallet.cpp
Old, non-standard name, using old structure of outputs.
=> replace serValue with amount(commitment)

src/qt/walletmodel.cpp
Doesn't compile. Oops. Leaving code in since I don't know what the correct behavior should be. (QT is unsupported)
=> fixup! Don't use pointers for CReserveKeys

.travis.yml, contrib/devtools/check-doc.py, qa/rpc-tests/test_framework/util.py, src/rpc/mining.cpp
Try more things on top of https://github.com/ElementsProject/elements/pull/229
=> Help fixing travis

.travis.yml, configure.ac, contrib/devtools/check-doc.py, qa/rpc-tests/listtransactions.py, src/rpc/mining.cpp, src/rpc/rawtransaction.cpp, src/secp256k1/src/modules/generator/Makefile.am.include, src/test/blind_tests.cpp
Accidentally merged in https://github.com/ElementsProject/elements/pull/242
Force pushed history back.
=> Fix Travis, part 2

qa/rpc-tests/pegging.py, src/init.cpp, src/script/interpreter.cpp, src/script/interpreter.h, src/script/script.h
=> Implement hidden arg to set parent confirmation depth requirements

src/test/blind_tests.cpp, src/validation.cpp
solves https://github.com/ElementsProject/elements/issues/261
=> don't assert false when checking commitment types

qa/rpc-tests/confidential_transactions.py, src/rpc/blockchain.cpp
Resolves https://github.com/ElementsProject/elements/issues/222
=> Reverse endianness of asset field in gettxout to match everywhere else

qa/rpc-tests/confidential_transactions.py
Small changes to do things more like they're done upstream in confidential_transactions.py
=> QA: Modernize confidential_transactions.py

qa/rpc-tests/pegging.py, src/rpc/blockchain.cpp
Useful, especially when there is no access to a wallet.
=> add getsidechaininfo RPC call

doc/man/bitcoin-qt.1, doc/man/bitcoind.1, qa/rpc-tests/bumpfee.py, src/wallet/wallet.cpp, src/wallet/wallet.h
=> Wallet: Remove -walletrbf option

src/init.cpp
=> list mainchain* commandline startup arguments

src/test/pegin_witness_tests.cpp, src/txmempool.cpp, src/validation.cpp, src/validation.h
solves https://github.com/ElementsProject/elements/issues/293
=> skip balance checks when assumevalid is active

src/wallet/rpcwallet.cpp
resolves https://github.com/ElementsProject/elements/issues/280
=> re-add transaction comments to univalue returns

qa/rpc-tests/pegging.py, src/rpc/protocol.cpp
Decouple GetMainchainAuthCookieFile() from the selected chain's datadir.
=> 2WP: -mainchainrpccookiefile defaults to regtest/.cookie for all chains

src/chainparamsbase.h
=> Chainparams: rename "main" to "___old_main" to avoid confusion

src/chainparams.cpp
=> Small fix to #306

qa/rpc-tests/pegging.py, src/wallet/rpcwallet.cpp
previous behavior gave a nearly wrong reason of invalid pegin witness
=> add better reject reason for immature peg-in, with test

qa/rpc-tests/pegging.py, src/rpc/client.cpp, src/wallet/rpcwallet.cpp
Most useful for "send all" type functionality.
=> add option to subtract fee from peg-out output amount

src/miner.cpp
Miner gives itself quite a bit of room for error in coinbase, but with large scripts/proofs we will need more.
This attempts to figure out how many signatures will be required, then pads the block weight to account for that.
In the future we should probably just remove all weight accounting from the challenge/proof.
=> fix miner block header proof accounting

qa/rpc-tests/wallet-hd.py
rough backport of https://github.com/bitcoin/bitcoin/pull/12947/
=> speedup and fix wallet-hd functional test for CA

qa/pull-tester/rpc-tests.py, qa/rpc-tests/feature_blocksign.py, qa/rpc-tests/test_framework/util.py
Let's add this test that @stevenroose wrote, I only slightly modified it.
Later I want to extend it to test things other than 3 of 3, including a single signer (without using multisig if it's 1 of 1).
=> QA: Introduce feature_blocksign.py

qa/pull-tester/rpc-tests.py
Just bikeshedding on the order of the tests, travis should thank this.
=> QA: Elements tests first

contrib/assets_tutorial/assets_tutorial.py, contrib/assets_tutorial/assets_tutorial.sh
Fixed issue where e2 couldn't claim anyone-can-spend coins as they all now initially reside in one address. Fixes issue #380
=> Fix issue #380 caused by change to initial free coins distribution

doc/elements-api.md
Might as well consolidate that one-file repo in here.
=> Move elementsbp-api-reference repo in doc/ dir

src/validation.cpp, src/validation.h
=> require 0.16.3 parent Core node

.travis.yml, src/primitives/transaction.h, src/txmempool.cpp, src/validation.cpp
`DEBUG=1` builds finally work in Travis.
=> fix various undefined behavior and null ptr dereferences

Makefile.am, test/bitcoin_functional/functional/test_framework/test_framework.py, test/bitcoin_functional/functional/test_framework/util.py, test/bitcoin_functional/functional/test_runner.py
We were just re-running the other tests.
=> Actually run the bitcoin functional tests with test_runner

qa/rpc-tests/feature_blocksign.py, src/blockencodings.cpp, src/blockencodings.h, src/miner.cpp, src/rpc/mining.cpp
Combined with https://github.com/ElementsProject/elements/pull/339 should be pretty powerful for speed of block proposal transmission.
=> compact block RPC calls

test/bitcoin_functional/functional/test_framework/netutil.py, test/functional/test_framework/netutil.py
Upstream: https://github.com/bitcoin/bitcoin/pull/13963
=> Replace deprecated tostring with tobytes

src/blind.cpp, src/validation.cpp
Shouldn't be an issue, but just as a precaution to protect against non-guaranteed conditions changing.
=> Use proper parsing API for generator comparison

src/pegins.cpp, src/pegins.h, src/script/interpreter.cpp, src/script/interpreter.h, src/script/standard.cpp, src/script/standard.h
And use it to sanity check startup constants.
=> [0.17] Add Liquid v1 based script matching functionality

src/validation.cpp
This condition is already checked two conditionals above.
=> remove redundant value validity check

test/functional/p2p_segwit.py
Backport of https://github.com/instagibbs/bitcoin/commit/7c1ad7c0367e94748e724d6a39d056b20ecc3975
=> [0.17] Add test for superfulous witness record in deserialization

src/primitives/transaction.h
Backport from upstream https://github.com/bitcoin/bitcoin/pull/14039
=> Disallow extended encoding for non-witness transactions

src/bitcoind.cpp, src/rpc/server.cpp
Resolves https://github.com/ElementsProject/elements/issues/555
=> Fix a few Bitcoin server strings

src/wallet/wallet.cpp
Resolves https://github.com/ElementsProject/elements/issues/571
=> Fix some const clang complaints

src/confidential_validation.cpp, src/validation.cpp, test/functional/feature_fedpeg.py, test/functional/feature_txwitness.py, test/functional/test_framework/messages.py
resolves https://github.com/ElementsProject/elements/issues/530
=> Add issuance serialization in python, tighten up DoS rules

src/wallet/wallet.cpp
This should result in better diagnosing of `fundrawtransaction` behavior in case of bugs with blinding.
=> CreateTransaction should still print blinded tx info during fundraw etc

contrib/gitian-descriptors/gitian-liquid-linux.yml, contrib/gitian-descriptors/gitian-liquid-osx.yml, contrib/gitian-descriptors/gitian-liquid-win.yml
resolves https://github.com/ElementsProject/elements/issues/592
=> Liquid gitian builds: move more to liquid name

contrib/gitian-descriptors/gitian-liquid-win.yml
resolves https://github.com/ElementsProject/elements/issues/603
=> gitian: Rename liquid windows installer to liquid

contrib/macdeploy/custom_dsstore.py
resolves https://github.com/ElementsProject/elements/issues/605
=> [cherry-pick] [macOS] Remove DS_Store WindowBounds bytes object

src/rpc/mining.cpp
https://github.com/ElementsProject/elements/issues/617
=> Changed combineblocksigs  example text to include updated pubkey/sig fields

src/chainparams.cpp, src/chainparamsbase.cpp, test/bitcoin_functional/functional/test_framework/util.py, test/functional/feature_assetsdir.py, test/functional/feature_confidential_transactions.py, test/functional/feature_connect_genesis_outputs.py, test/functional/feature_default_asset_name.py, test/functional/feature_initial_reissuance_token.py, test/functional/test_framework/util.py, test/functional/test_runner.py
=> Rename -con_connect_coinbase to -con_connect_genesis_outputs

src/interfaces/wallet.cpp, src/interfaces/wallet.h, src/qt/transactiondesc.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
First commit is dead code that we don't want to accidentally try to use.
Second fixes actually-used code in QT for looking at transaction details.
resolves https://github.com/ElementsProject/elements/issues/630
=> Fixup some QT-only credit computing code

contrib/gitian-descriptors/gitian-liquid-win.yml
resolves https://github.com/ElementsProject/elements/issues/603
=> Properly rename liquid windows binaries

src/wallet/rpcwallet.cpp
=> [0.17 backport]  Disallow issuance calls in bitcoin mode

contrib/gitian-descriptors/gitian-liquid-win.yml
=> [0.17 backport] Properly rename liquid windows binaries

src/test/util_tests.cpp, src/util.cpp
backport of https://github.com/ElementsProject/elements/pull/675
=> [backport 0.17] Change default chain to liquidv1

src/test/util_tests.cpp, src/util/system.cpp
backport of https://github.com/ElementsProject/elements/pull/675
=> [backport 0.18] Change default chain to liquidv1

src/rpc/server.cpp, src/wallet/rpcwallet.cpp, test/functional/feature_pak.py
resolves https://github.com/ElementsProject/elements/issues/695
and also fixes RPC port in help
needs backport to 0.17/0.18
=> sendtomainchain with pak and subtract fee from output fix

src/interfaces/wallet.cpp, src/qt/networkstyle.cpp
resolves https://github.com/ElementsProject/elements/issues/692
=> Qt fixes post 18

src/rpc/server.cpp, src/wallet/rpcwallet.cpp, test/functional/feature_pak.py
regression introduced in 0.17 catchup with the convergence of liquid and elements codebases.
=> [0.17] sendtomainchain pak fix

src/wallet/rpcwallet.cpp, test/functional/feature_pak.py
=> [0.18 backport] sendtomainchain_pak: Fix minimum send amount message

src/chainparams.cpp, src/chainparamsbase.cpp
Needs backport for 0.18.1 release
=> Add legacy pak arg for custom chains

src/block_proof.cpp, src/hash.h, src/rpc/mining.cpp, src/script/generic.hpp, src/wallet/rpcwallet.cpp
=> [0.18 backport] [HF] Dynafed blocks must have sighash byte #723

src/psbt.h
Backport of https://github.com/ElementsProject/elements/pull/730
=> [0.18] Change Proprietary types to use the method specified in BIP 174

test/functional/feature_blocksign.py
Backport of https://github.com/ElementsProject/elements/pull/747
=> [0.18] feature_blocksign.py: Allot for possibility of non-empty block 0.5RTT

src/rpc/blockchain.cpp
backport of https://github.com/ElementsProject/elements/pull/758
=> [0.18] dynaParamsToJSON: No lock required

src/chainparams.cpp, src/init.cpp
Needed for new release:
https://github.com/ElementsProject/elements/pull/768
https://github.com/ElementsProject/elements/pull/769
https://github.com/ElementsProject/elements/pull/770
=> 0.18 backports

src/rpc/mining.cpp
fixes https://github.com/ElementsProject/elements/issues/775#event-2795298661
=> commit_data is entirely optional

src/chainparams.cpp, src/consensus/params.h, src/versionbits.cpp, test/functional/feature_dynafed.py
When based on block time, it's really hard to engineer principled tests for activation of consensus changes.
resolves https://github.com/ElementsProject/elements/issues/779
=> Change elements mode to activating BIP9 signaling based on height

src/chainparams.cpp, src/consensus/params.h, src/versionbits.cpp, test/functional/feature_dynafed.py
backport of https://github.com/ElementsProject/elements/pull/780
=> [0.18] Change elements mode to activating BIP9 signaling based on height

src/chainparams.cpp
fixes https://github.com/ElementsProject/elements/issues/765
=> Fill out expected liquidv1 chain size

test/bitcoin_functional/functional/rpc_fundrawtransaction.py, test/functional/rpc_fundrawtransaction.py
fixes tests after https://github.com/ElementsProject/elements/pull/778
=> Fix address string assertions in tests

src/chainparams.cpp, src/qt/forms/overviewpage.ui, src/qt/overviewpage.cpp, src/qt/receiverequestdialog.cpp, src/wallet/rpcwallet.cpp, test/bitcoin_functional/functional/rpc_fundrawtransaction.py, test/functional/rpc_fundrawtransaction.py
backports of:
- https://github.com/ElementsProject/elements/pull/788 
- https://github.com/ElementsProject/elements/pull/785
- https://github.com/ElementsProject/elements/pull/784
- https://github.com/ElementsProject/elements/pull/778
=> [0.18] Backports of various UX fixes

src/rpc/blockchain.cpp
backport of https://github.com/ElementsProject/elements/pull/799
=> [0.18] Add current_params_root key to getblockchaininfo

src/bitcoin-cli.cpp, src/chainparamsbase.cpp, src/chainparamsbase.h, src/init.cpp, src/qt/guiutil.cpp, src/test/util_tests.cpp, src/util/system.cpp, src/util/system.h
Backport of https://github.com/ElementsProject/elements/pull/808.
=> [0.18] Backport of 'Add DEFAULT chain and set to liquidv1'

src/wallet/rpcwallet.cpp
Band aid for https://github.com/ElementsProject/elements/issues/824
=> Create witness outputs for (re)issueasset RPC

src/httpserver.cpp
Backport of https://github.com/ElementsProject/elements/pull/819
=> [0.18 backport] Include deque to fix build

src/httpserver.cpp
Upstream: https://github.com/bitcoin/bitcoin/pull/17249/files
=> Include deque to fix build

src/wallet/rpcwallet.cpp
Before anything is written to wallet.
=> initpegoutwallet: check for hardened derivation steps early

test/functional/wallet_balance.py
Addresses https://github.com/ElementsProject/elements/issues/827.
=> Add test to test unconfirmed asset balances

src/init.cpp
=> Trivial: fix typo in error message when mainchain daemon is unavailable

src/wallet/rpcwallet.cpp
resolves https://github.com/ElementsProject/elements/issues/794
=> Remove outdated information about peg-in address creation pre-HD

src/blind.h, src/policy/fees.cpp, src/policy/fees.h, src/wallet/wallet.cpp
=> [0.18 backport] Support fee estimation for fees lower than 1 sat/byte

src/bench/verify_script.cpp, src/script/generic.hpp, src/script/interpreter.cpp, src/script/interpreter.h, src/script/sign.cpp, src/script/sign.h, src/test/multisig_tests.cpp, src/test/script_tests.cpp, src/test/sighash_tests.cpp, src/test/txvalidationcache_tests.cpp, src/validation.cpp, test/functional/feature_sighash_rangeproof.py, test/functional/feature_txwitness.py, test/functional/test_framework/address.py, test/functional/test_framework/key.py, test/functional/test_framework/messages.py, test/functional/test_framework/script.py, test/functional/test_runner.py
=> [elements-0.18]  Add SIGHASH_RANGEPROOF support

test/functional/feature_dynafed.py
I noticed this scenario was not really tested in the test
=> Test duration of fedpeg validity in dynafed test

src/chainparams.cpp, src/chainparamsbase.cpp, src/chainparamsbase.h
=> [elements-0.18]  Add liquidv1test chainparams

src/chainparamsbase.cpp, src/validation.cpp, test/functional/feature_blocksign.py, test/functional/feature_dynafed.py, test/functional/feature_sighash_rangeproof.py, test/functional/rpc_tweakfedpeg.py
=> [elements-0.18]  Undo default signalling behavior for dynafed unless enabled

src/validation.cpp
Relating https://github.com/ElementsProject/elements/issues/981.
Needs forward port.
=> [elements-0.18] Add logging for dynafed activation and transitions

src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, test/functional/feature_issuance.py
Relating https://github.com/ElementsProject/elements/issues/985.
Needs forward port.
=> [elements-0.18] Support supplying contract hash to issueasset RPC

src/validation.cpp
Forward port and fixup of https://github.com/ElementsProject/elements/pull/994.
Closes https://github.com/ElementsProject/elements/issues/981.
=> [forward port] Add logging for dynafed activation and transitions

contrib/assets_tutorial/assets_tutorial.py, contrib/assets_tutorial/bitcoin.conf, contrib/assets_tutorial/elements1.conf, contrib/assets_tutorial/elements2.conf
Clean up and rewrite the assets tutorial
* Updates RPC to handle 0.21 changes (you now need createwallet/loadwallet)
* Cleans up stray processes and temp directories even when it crashes
* Significantly expands comments
* Modernizes the Python, removes weird idioms like calling `raise` in an `except: pass` block
=> Rewrite assets tutorial

contrib/assets_tutorial/assets_tutorial.py, contrib/assets_tutorial/pset_swap_tutorial.py, contrib/assets_tutorial/test_framework/daemon.py, src/node/psbt.cpp
Adds a second executable tutorial which uses the PSET API to produce a swap transaction.
=> Add 2-party blinded coinjoin PSET tutorial

src/psbt.cpp, src/script/interpreter.cpp, src/script/sign.cpp, src/validation.cpp, test/functional/feature_confidential_transactions.py, test/functional/feature_sighash_rangeproof.py, test/functional/test_framework/script.py
=> Fix SIGHASH_RANGEPROOF bugs

src/blindpsbt.cpp, src/util/error.cpp, src/util/error.h, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, test/functional/rpc_psbt.py
Fixes #1049 
Needs backport to 0.21 (and a new rc).
Although there are several bugs here, none affect the functionaries. There is a more thorough summary in the second-to-last commit message.
=> wallet: fix a pile of bugs in transaction funding logic

src/validation.cpp
Leftover change from https://github.com/ElementsProject/elements/pull/1062
=> Remove obsolete comment after a06aac152a0b3535890c6a1f0118b255838ae6c5

src/net.h, test/bitcoin_functional/functional/p2p_invalid_messages.py, test/functional/test_framework/messages.py
=> Raise max P2P message size to account for larger elements dynafed header size.

src/script/interpreter.cpp
In elements tapscript is verison 0xc4
=> Fix tapscript comment

src/rpc/request.cpp, src/util/system.cpp, src/util/system.h
Fixes: https://github.com/ElementsProject/elements/issues/1120
=> Fix location for default cookie path

src/qt/res/bitcoin-qt-res.rc
Fixes: https://github.com/ElementsProject/elements/issues/1164
The "before" can be seen in issue https://github.com/ElementsProject/elements/issues/1164
=> Fix company for Windows exes

src/rpc/blockchain.cpp
Fixes: https://github.com/ElementsProject/elements/issues/1193
=> Add missing field 'signblock_challenge' back to getblock

src/rpc/util.cpp
Remove duplicated code that looks like a bad merge in the 21-22 timeframe
=> Remove duplicated code from merge

src/qt/sendcoinsdialog.cpp
Fixes: https://github.com/ElementsProject/elements/issues/1220
=> Elements-qt: Avoid mixing assets when using all the available balance

src/rpc/blockchain.cpp, test/functional/feature_dynafed.py
Fixes: https://github.com/ElementsProject/elements/issues/1230
Related to: https://github.com/ElementsProject/elements/pull/1114
=> Fix dynamic parameters root in getblockheader

src/qt/bitcoinunits.cpp
Fixes: https://github.com/ElementsProject/elements/issues/1234
=> Elements-qt: Show correct default asset name

test/lint/lint-files.py
Fix the CI that currently fails on the simplicity branch.
=> Fix CI on simplicity branch

src/wallet/rpcwallet.cpp
Version of https://github.com/ElementsProject/elements/pull/1294 for 22.x
=> [22.x] Remove constraint on liquidv1 pegout bitcoin descriptor

src/chainparams.cpp
fix a typo: `encumberance`->`encumbrance`
=> chore: fix typos

src/node/miner.cpp, test/functional/feature_discount_ct.py
related to #1317 
Discount CT at the nominal `blockmintxfee` have a lower real feerate and are not included by the miner in the block template.
If `acceptdiscountct` is enabled, use the discountvsize of the package instead of vsize.
=> fix: use discountvsize in miner if discount enabled

src/chainparams.cpp, src/init.cpp
Fixes: https://github.com/ElementsProject/elements/issues/1377
=> Master discountct liquidv1

src/rpc/rawtransaction.cpp, test/functional/rpc_psbt.py
=> decodepsbt: add asset/assetcommitment to input.witness_utxo

.cirrus.yml, configure.ac, src/chainparamsbase.h, src/node/ui_interface.h, src/support/lockedpool.cpp, src/support/lockedpool.h, src/test/system_tests.cpp, src/util/bip32.h, src/util/string.h, src/util/system.cpp, src/zmq/zmqabstractnotifier.h, src/zmq/zmqpublishnotifier.h
Cherry pick some commits from 23.x to fix master build in newer environments, also fixes the build with gcc-15
Fixes: https://github.com/ElementsProject/elements/issues/1398
=> Fix build in master with newer environments

ci/test/00_setup_env_mac_native_arm64.sh, ci/test/04_install.sh
This is just a cherry-pick of https://github.com/ElementsProject/elements/pull/1397 for 23.2.x release
=> Apply #1397 to 23.2.x

README.md
=> chore: replaced the non-working travis badge with a release
